/*
 * GeoServer Catalog Model
 * GeoServer Catalog Model Objects
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.geoserver.openapi.model.catalog;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * WMS attribution information to be drawn on each map
 */
@ApiModel(description = "WMS attribution information to be drawn on each map")
@JsonPropertyOrder({
  AttributionInfo.JSON_PROPERTY_TITLE,
  AttributionInfo.JSON_PROPERTY_HREF,
  AttributionInfo.JSON_PROPERTY_LOGO_U_R_L,
  AttributionInfo.JSON_PROPERTY_LOGO_WIDTH,
  AttributionInfo.JSON_PROPERTY_LOGO_HEIGHT,
  AttributionInfo.JSON_PROPERTY_LOGO_TYPE
})

public class AttributionInfo {
  public static final String JSON_PROPERTY_TITLE = "title";
  private String title;

  public static final String JSON_PROPERTY_HREF = "href";
  private String href;

  public static final String JSON_PROPERTY_LOGO_U_R_L = "logoURL";
  private String logoURL;

  public static final String JSON_PROPERTY_LOGO_WIDTH = "logoWidth";
  private Integer logoWidth;

  public static final String JSON_PROPERTY_LOGO_HEIGHT = "logoHeight";
  private Integer logoHeight;

  public static final String JSON_PROPERTY_LOGO_TYPE = "logoType";
  private String logoType;


  public AttributionInfo title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Human-readable text describing the data provider
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Human-readable text describing the data provider")
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public AttributionInfo href(String href) {
    
    this.href = href;
    return this;
  }

   /**
   * URL to data provider
   * @return href
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "URL to data provider")
  @JsonProperty(JSON_PROPERTY_HREF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHref() {
    return href;
  }


  public void setHref(String href) {
    this.href = href;
  }


  public AttributionInfo logoURL(String logoURL) {
    
    this.logoURL = logoURL;
    return this;
  }

   /**
   * Data provider logo
   * @return logoURL
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Data provider logo")
  @JsonProperty(JSON_PROPERTY_LOGO_U_R_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLogoURL() {
    return logoURL;
  }


  public void setLogoURL(String logoURL) {
    this.logoURL = logoURL;
  }


  public AttributionInfo logoWidth(Integer logoWidth) {
    
    this.logoWidth = logoWidth;
    return this;
  }

   /**
   * Data provider logo width
   * @return logoWidth
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Data provider logo width")
  @JsonProperty(JSON_PROPERTY_LOGO_WIDTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLogoWidth() {
    return logoWidth;
  }


  public void setLogoWidth(Integer logoWidth) {
    this.logoWidth = logoWidth;
  }


  public AttributionInfo logoHeight(Integer logoHeight) {
    
    this.logoHeight = logoHeight;
    return this;
  }

   /**
   * Data provider logo height
   * @return logoHeight
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Data provider logo height")
  @JsonProperty(JSON_PROPERTY_LOGO_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLogoHeight() {
    return logoHeight;
  }


  public void setLogoHeight(Integer logoHeight) {
    this.logoHeight = logoHeight;
  }


  public AttributionInfo logoType(String logoType) {
    
    this.logoType = logoType;
    return this;
  }

   /**
   * Format of data provider logo, example \&quot;image/png\&quot;
   * @return logoType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Format of data provider logo, example \"image/png\"")
  @JsonProperty(JSON_PROPERTY_LOGO_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLogoType() {
    return logoType;
  }


  public void setLogoType(String logoType) {
    this.logoType = logoType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AttributionInfo attributionInfo = (AttributionInfo) o;
    return Objects.equals(this.title, attributionInfo.title) &&
        Objects.equals(this.href, attributionInfo.href) &&
        Objects.equals(this.logoURL, attributionInfo.logoURL) &&
        Objects.equals(this.logoWidth, attributionInfo.logoWidth) &&
        Objects.equals(this.logoHeight, attributionInfo.logoHeight) &&
        Objects.equals(this.logoType, attributionInfo.logoType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, href, logoURL, logoWidth, logoHeight, logoType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AttributionInfo {\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    logoURL: ").append(toIndentedString(logoURL)).append("\n");
    sb.append("    logoWidth: ").append(toIndentedString(logoWidth)).append("\n");
    sb.append("    logoHeight: ").append(toIndentedString(logoHeight)).append("\n");
    sb.append("    logoType: ").append(toIndentedString(logoType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

