/*
 * GeoServer Catalog Model
 * GeoServer Catalog Model Objects
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.geoserver.openapi.model.catalog;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * AuthorityURLInfo
 */
@JsonPropertyOrder({
  AuthorityURLInfo.JSON_PROPERTY_NAME,
  AuthorityURLInfo.JSON_PROPERTY_HREF
})

public class AuthorityURLInfo {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_HREF = "href";
  private String href;


  public AuthorityURLInfo name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Authory name, describing the industry, national or international origanization responsible for data product standard.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Authory name, describing the industry, national or international origanization responsible for data product standard.")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public AuthorityURLInfo href(String href) {
    
    this.href = href;
    return this;
  }

   /**
   * URL to authority organization
   * @return href
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "URL to authority organization")
  @JsonProperty(JSON_PROPERTY_HREF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHref() {
    return href;
  }


  public void setHref(String href) {
    this.href = href;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthorityURLInfo authorityURLInfo = (AuthorityURLInfo) o;
    return Objects.equals(this.name, authorityURLInfo.name) &&
        Objects.equals(this.href, authorityURLInfo.href);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, href);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthorityURLInfo {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

