/*
 * GeoServer Catalog Model
 * GeoServer Catalog Model Objects
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.geoserver.openapi.model.catalog;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.geoserver.openapi.model.catalog.CoverageDimensionInfo;
import org.geoserver.openapi.model.catalog.CoverageInfoAllOf;
import org.geoserver.openapi.model.catalog.CoverageStoreInfo;
import org.geoserver.openapi.model.catalog.DataLinkInfo;
import org.geoserver.openapi.model.catalog.EnvelopeInfo;
import org.geoserver.openapi.model.catalog.KeywordInfo;
import org.geoserver.openapi.model.catalog.MetadataLinks;
import org.geoserver.openapi.model.catalog.MetadataMap;
import org.geoserver.openapi.model.catalog.NamespaceInfo;
import org.geoserver.openapi.model.catalog.ProjectionPolicy;
import org.geoserver.openapi.model.catalog.ResourceInfo;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * CoverageInfo
 */
@JsonPropertyOrder({
  CoverageInfo.JSON_PROPERTY_NAME,
  CoverageInfo.JSON_PROPERTY_NATIVE_NAME,
  CoverageInfo.JSON_PROPERTY_NAMESPACE,
  CoverageInfo.JSON_PROPERTY_TITLE,
  CoverageInfo.JSON_PROPERTY_ABSTRACT,
  CoverageInfo.JSON_PROPERTY_DESCRIPTION,
  CoverageInfo.JSON_PROPERTY_ENABLED,
  CoverageInfo.JSON_PROPERTY_ALIAS,
  CoverageInfo.JSON_PROPERTY_DATA_LINKS,
  CoverageInfo.JSON_PROPERTY_DISABLED_SERVICES,
  CoverageInfo.JSON_PROPERTY_KEYWORDS,
  CoverageInfo.JSON_PROPERTY_LAT_LON_BOUNDING_BOX,
  CoverageInfo.JSON_PROPERTY_NATIVE_BOUNDING_BOX,
  CoverageInfo.JSON_PROPERTY_METADATA,
  CoverageInfo.JSON_PROPERTY_METADATA_LINKS,
  CoverageInfo.JSON_PROPERTY_NATIVE_C_R_S,
  CoverageInfo.JSON_PROPERTY_SRS,
  CoverageInfo.JSON_PROPERTY_PROJECTION_POLICY,
  CoverageInfo.JSON_PROPERTY_ADVERTISED,
  CoverageInfo.JSON_PROPERTY_SERVICE_CONFIGURATION,
  CoverageInfo.JSON_PROPERTY_STORE,
  CoverageInfo.JSON_PROPERTY_NATIVE_COVERAGE_NAME,
  CoverageInfo.JSON_PROPERTY_NATIVE_FORMAT,
  CoverageInfo.JSON_PROPERTY_SUPPORTED_FORMATS,
  CoverageInfo.JSON_PROPERTY_REQUEST_S_R_S,
  CoverageInfo.JSON_PROPERTY_RESPONSE_S_R_S,
  CoverageInfo.JSON_PROPERTY_DEFAULT_INTERPOLATION_METHOD,
  CoverageInfo.JSON_PROPERTY_INTERPOLATION_METHODS,
  CoverageInfo.JSON_PROPERTY_PARAMETERS,
  CoverageInfo.JSON_PROPERTY_DIMENSIONS
})

public class CoverageInfo {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_NATIVE_NAME = "nativeName";
  private String nativeName;

  public static final String JSON_PROPERTY_NAMESPACE = "namespace";
  private NamespaceInfo namespace;

  public static final String JSON_PROPERTY_TITLE = "title";
  private String title;

  public static final String JSON_PROPERTY_ABSTRACT = "abstract";
  private String _abstract;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_ENABLED = "enabled";
  private Boolean enabled;

  public static final String JSON_PROPERTY_ALIAS = "alias";
  private List<String> alias = null;

  public static final String JSON_PROPERTY_DATA_LINKS = "dataLinks";
  private List<DataLinkInfo> dataLinks = null;

  public static final String JSON_PROPERTY_DISABLED_SERVICES = "disabledServices";
  private List<String> disabledServices = null;

  public static final String JSON_PROPERTY_KEYWORDS = "keywords";
  private List<KeywordInfo> keywords = null;

  public static final String JSON_PROPERTY_LAT_LON_BOUNDING_BOX = "latLonBoundingBox";
  private EnvelopeInfo latLonBoundingBox;

  public static final String JSON_PROPERTY_NATIVE_BOUNDING_BOX = "nativeBoundingBox";
  private EnvelopeInfo nativeBoundingBox;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  private MetadataMap metadata;

  public static final String JSON_PROPERTY_METADATA_LINKS = "metadataLinks";
  private MetadataLinks metadataLinks;

  public static final String JSON_PROPERTY_NATIVE_C_R_S = "nativeCRS";
  private String nativeCRS;

  public static final String JSON_PROPERTY_SRS = "srs";
  private String srs;

  public static final String JSON_PROPERTY_PROJECTION_POLICY = "projectionPolicy";
  private ProjectionPolicy projectionPolicy;

  public static final String JSON_PROPERTY_ADVERTISED = "advertised";
  private Boolean advertised;

  public static final String JSON_PROPERTY_SERVICE_CONFIGURATION = "serviceConfiguration";
  private Boolean serviceConfiguration;

  public static final String JSON_PROPERTY_STORE = "store";
  private CoverageStoreInfo store;

  public static final String JSON_PROPERTY_NATIVE_COVERAGE_NAME = "nativeCoverageName";
  private String nativeCoverageName;

  public static final String JSON_PROPERTY_NATIVE_FORMAT = "nativeFormat";
  private String nativeFormat;

  public static final String JSON_PROPERTY_SUPPORTED_FORMATS = "supportedFormats";
  private List<String> supportedFormats = null;

  public static final String JSON_PROPERTY_REQUEST_S_R_S = "requestSRS";
  private List<String> requestSRS = null;

  public static final String JSON_PROPERTY_RESPONSE_S_R_S = "responseSRS";
  private List<String> responseSRS = null;

  public static final String JSON_PROPERTY_DEFAULT_INTERPOLATION_METHOD = "defaultInterpolationMethod";
  private String defaultInterpolationMethod;

  public static final String JSON_PROPERTY_INTERPOLATION_METHODS = "interpolationMethods";
  private List<String> interpolationMethods = null;

  public static final String JSON_PROPERTY_PARAMETERS = "parameters";
  private Map<String, Object> parameters = null;

  public static final String JSON_PROPERTY_DIMENSIONS = "dimensions";
  private List<CoverageDimensionInfo> dimensions = null;


  public CoverageInfo name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the resource. This name corresponds to the \&quot;published\&quot; name of the resource.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the resource. This name corresponds to the \"published\" name of the resource.")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public CoverageInfo nativeName(String nativeName) {
    
    this.nativeName = nativeName;
    return this;
  }

   /**
   * The native name of the resource. This name corresponds to the physical resource that feature type is derived from -- a shapefile name, a database table, etc...
   * @return nativeName
  **/
  @ApiModelProperty(required = true, value = "The native name of the resource. This name corresponds to the physical resource that feature type is derived from -- a shapefile name, a database table, etc...")
  @JsonProperty(JSON_PROPERTY_NATIVE_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNativeName() {
    return nativeName;
  }


  public void setNativeName(String nativeName) {
    this.nativeName = nativeName;
  }


  public CoverageInfo namespace(NamespaceInfo namespace) {
    
    this.namespace = namespace;
    return this;
  }

   /**
   * Get namespace
   * @return namespace
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAMESPACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public NamespaceInfo getNamespace() {
    return namespace;
  }


  public void setNamespace(NamespaceInfo namespace) {
    this.namespace = namespace;
  }


  public CoverageInfo title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * The title of the resource.
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The title of the resource.")
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public CoverageInfo _abstract(String _abstract) {
    
    this._abstract = _abstract;
    return this;
  }

   /**
   * the abstract for the resource.
   * @return _abstract
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "the abstract for the resource.")
  @JsonProperty(JSON_PROPERTY_ABSTRACT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAbstract() {
    return _abstract;
  }


  public void setAbstract(String _abstract) {
    this._abstract = _abstract;
  }


  public CoverageInfo description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * A description of the resource. This is usually something that is to be displayed in a user interface.
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A description of the resource. This is usually something that is to be displayed in a user interface.")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public CoverageInfo enabled(Boolean enabled) {
    
    this.enabled = enabled;
    return this;
  }

   /**
   * A flag indicating if the resource is enabled or not.
   * @return enabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A flag indicating if the resource is enabled or not.")
  @JsonProperty(JSON_PROPERTY_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEnabled() {
    return enabled;
  }


  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }


  public CoverageInfo alias(List<String> alias) {
    
    this.alias = alias;
    return this;
  }

  public CoverageInfo addAliasItem(String aliasItem) {
    if (this.alias == null) {
      this.alias = new ArrayList<>();
    }
    this.alias.add(aliasItem);
    return this;
  }

   /**
   * A set of aliases or alternative names that the resource is also known by.
   * @return alias
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A set of aliases or alternative names that the resource is also known by.")
  @JsonProperty(JSON_PROPERTY_ALIAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getAlias() {
    return alias;
  }


  public void setAlias(List<String> alias) {
    this.alias = alias;
  }


  public CoverageInfo dataLinks(List<DataLinkInfo> dataLinks) {
    
    this.dataLinks = dataLinks;
    return this;
  }

  public CoverageInfo addDataLinksItem(DataLinkInfo dataLinksItem) {
    if (this.dataLinks == null) {
      this.dataLinks = new ArrayList<>();
    }
    this.dataLinks.add(dataLinksItem);
    return this;
  }

   /**
   * A collection of data links for the resource.
   * @return dataLinks
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A collection of data links for the resource.")
  @JsonProperty(JSON_PROPERTY_DATA_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DataLinkInfo> getDataLinks() {
    return dataLinks;
  }


  public void setDataLinks(List<DataLinkInfo> dataLinks) {
    this.dataLinks = dataLinks;
  }


  public CoverageInfo disabledServices(List<String> disabledServices) {
    
    this.disabledServices = disabledServices;
    return this;
  }

  public CoverageInfo addDisabledServicesItem(String disabledServicesItem) {
    if (this.disabledServices == null) {
      this.disabledServices = new ArrayList<>();
    }
    this.disabledServices.add(disabledServicesItem);
    return this;
  }

   /**
   * a list of disabled services names for this resource (e.g. [WMS, WCS])
   * @return disabledServices
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "a list of disabled services names for this resource (e.g. [WMS, WCS])")
  @JsonProperty(JSON_PROPERTY_DISABLED_SERVICES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getDisabledServices() {
    return disabledServices;
  }


  public void setDisabledServices(List<String> disabledServices) {
    this.disabledServices = disabledServices;
  }


  public CoverageInfo keywords(List<KeywordInfo> keywords) {
    
    this.keywords = keywords;
    return this;
  }

  public CoverageInfo addKeywordsItem(KeywordInfo keywordsItem) {
    if (this.keywords == null) {
      this.keywords = new ArrayList<>();
    }
    this.keywords.add(keywordsItem);
    return this;
  }

   /**
   * A collection of keywords associated with the resource.
   * @return keywords
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A collection of keywords associated with the resource.")
  @JsonProperty(JSON_PROPERTY_KEYWORDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<KeywordInfo> getKeywords() {
    return keywords;
  }


  public void setKeywords(List<KeywordInfo> keywords) {
    this.keywords = keywords;
  }


  public CoverageInfo latLonBoundingBox(EnvelopeInfo latLonBoundingBox) {
    
    this.latLonBoundingBox = latLonBoundingBox;
    return this;
  }

   /**
   * Get latLonBoundingBox
   * @return latLonBoundingBox
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LAT_LON_BOUNDING_BOX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EnvelopeInfo getLatLonBoundingBox() {
    return latLonBoundingBox;
  }


  public void setLatLonBoundingBox(EnvelopeInfo latLonBoundingBox) {
    this.latLonBoundingBox = latLonBoundingBox;
  }


  public CoverageInfo nativeBoundingBox(EnvelopeInfo nativeBoundingBox) {
    
    this.nativeBoundingBox = nativeBoundingBox;
    return this;
  }

   /**
   * Get nativeBoundingBox
   * @return nativeBoundingBox
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NATIVE_BOUNDING_BOX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EnvelopeInfo getNativeBoundingBox() {
    return nativeBoundingBox;
  }


  public void setNativeBoundingBox(EnvelopeInfo nativeBoundingBox) {
    this.nativeBoundingBox = nativeBoundingBox;
  }


  public CoverageInfo metadata(MetadataMap metadata) {
    
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MetadataMap getMetadata() {
    return metadata;
  }


  public void setMetadata(MetadataMap metadata) {
    this.metadata = metadata;
  }


  public CoverageInfo metadataLinks(MetadataLinks metadataLinks) {
    
    this.metadataLinks = metadataLinks;
    return this;
  }

   /**
   * Get metadataLinks
   * @return metadataLinks
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_METADATA_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MetadataLinks getMetadataLinks() {
    return metadataLinks;
  }


  public void setMetadataLinks(MetadataLinks metadataLinks) {
    this.metadataLinks = metadataLinks;
  }


  public CoverageInfo nativeCRS(String nativeCRS) {
    
    this.nativeCRS = nativeCRS;
    return this;
  }

   /**
   * The native coordinate reference system object of the resource, in WKT format
   * @return nativeCRS
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The native coordinate reference system object of the resource, in WKT format")
  @JsonProperty(JSON_PROPERTY_NATIVE_C_R_S)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNativeCRS() {
    return nativeCRS;
  }


  public void setNativeCRS(String nativeCRS) {
    this.nativeCRS = nativeCRS;
  }


  public CoverageInfo srs(String srs) {
    
    this.srs = srs;
    return this;
  }

   /**
   * Returns the identifier of coordinate reference system of the resource.
   * @return srs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Returns the identifier of coordinate reference system of the resource.")
  @JsonProperty(JSON_PROPERTY_SRS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSrs() {
    return srs;
  }


  public void setSrs(String srs) {
    this.srs = srs;
  }


  public CoverageInfo projectionPolicy(ProjectionPolicy projectionPolicy) {
    
    this.projectionPolicy = projectionPolicy;
    return this;
  }

   /**
   * Get projectionPolicy
   * @return projectionPolicy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PROJECTION_POLICY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ProjectionPolicy getProjectionPolicy() {
    return projectionPolicy;
  }


  public void setProjectionPolicy(ProjectionPolicy projectionPolicy) {
    this.projectionPolicy = projectionPolicy;
  }


  public CoverageInfo advertised(Boolean advertised) {
    
    this.advertised = advertised;
    return this;
  }

   /**
   * true if the resource existence should be advertised (true by default, unless otherwise set)
   * @return advertised
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "true if the resource existence should be advertised (true by default, unless otherwise set)")
  @JsonProperty(JSON_PROPERTY_ADVERTISED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAdvertised() {
    return advertised;
  }


  public void setAdvertised(Boolean advertised) {
    this.advertised = advertised;
  }


  public CoverageInfo serviceConfiguration(Boolean serviceConfiguration) {
    
    this.serviceConfiguration = serviceConfiguration;
    return this;
  }

   /**
   * true if the resource will configure services access, false otherwise
   * @return serviceConfiguration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "true if the resource will configure services access, false otherwise")
  @JsonProperty(JSON_PROPERTY_SERVICE_CONFIGURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getServiceConfiguration() {
    return serviceConfiguration;
  }


  public void setServiceConfiguration(Boolean serviceConfiguration) {
    this.serviceConfiguration = serviceConfiguration;
  }


  public CoverageInfo store(CoverageStoreInfo store) {
    
    this.store = store;
    return this;
  }

   /**
   * Get store
   * @return store
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CoverageStoreInfo getStore() {
    return store;
  }


  public void setStore(CoverageStoreInfo store) {
    this.store = store;
  }


  public CoverageInfo nativeCoverageName(String nativeCoverageName) {
    
    this.nativeCoverageName = nativeCoverageName;
    return this;
  }

   /**
   * the native coverage name (used to pick up a specific coverage from within a reader)
   * @return nativeCoverageName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "the native coverage name (used to pick up a specific coverage from within a reader)")
  @JsonProperty(JSON_PROPERTY_NATIVE_COVERAGE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNativeCoverageName() {
    return nativeCoverageName;
  }


  public void setNativeCoverageName(String nativeCoverageName) {
    this.nativeCoverageName = nativeCoverageName;
  }


  public CoverageInfo nativeFormat(String nativeFormat) {
    
    this.nativeFormat = nativeFormat;
    return this;
  }

   /**
   * The native format name of the coverage
   * @return nativeFormat
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The native format name of the coverage")
  @JsonProperty(JSON_PROPERTY_NATIVE_FORMAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNativeFormat() {
    return nativeFormat;
  }


  public void setNativeFormat(String nativeFormat) {
    this.nativeFormat = nativeFormat;
  }


  public CoverageInfo supportedFormats(List<String> supportedFormats) {
    
    this.supportedFormats = supportedFormats;
    return this;
  }

  public CoverageInfo addSupportedFormatsItem(String supportedFormatsItem) {
    if (this.supportedFormats == null) {
      this.supportedFormats = new ArrayList<>();
    }
    this.supportedFormats.add(supportedFormatsItem);
    return this;
  }

   /**
   * The supported formats for the coverage
   * @return supportedFormats
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The supported formats for the coverage")
  @JsonProperty(JSON_PROPERTY_SUPPORTED_FORMATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getSupportedFormats() {
    return supportedFormats;
  }


  public void setSupportedFormats(List<String> supportedFormats) {
    this.supportedFormats = supportedFormats;
  }


  public CoverageInfo requestSRS(List<String> requestSRS) {
    
    this.requestSRS = requestSRS;
    return this;
  }

  public CoverageInfo addRequestSRSItem(String requestSRSItem) {
    if (this.requestSRS == null) {
      this.requestSRS = new ArrayList<>();
    }
    this.requestSRS.add(requestSRSItem);
    return this;
  }

   /**
   * The collection of identifiers of the crs&#39;s the coverage supports in a request.
   * @return requestSRS
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The collection of identifiers of the crs's the coverage supports in a request.")
  @JsonProperty(JSON_PROPERTY_REQUEST_S_R_S)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getRequestSRS() {
    return requestSRS;
  }


  public void setRequestSRS(List<String> requestSRS) {
    this.requestSRS = requestSRS;
  }


  public CoverageInfo responseSRS(List<String> responseSRS) {
    
    this.responseSRS = responseSRS;
    return this;
  }

  public CoverageInfo addResponseSRSItem(String responseSRSItem) {
    if (this.responseSRS == null) {
      this.responseSRS = new ArrayList<>();
    }
    this.responseSRS.add(responseSRSItem);
    return this;
  }

   /**
   * The collection of identifiers of the crs&#39;s the coverage supports in a response.
   * @return responseSRS
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The collection of identifiers of the crs's the coverage supports in a response.")
  @JsonProperty(JSON_PROPERTY_RESPONSE_S_R_S)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getResponseSRS() {
    return responseSRS;
  }


  public void setResponseSRS(List<String> responseSRS) {
    this.responseSRS = responseSRS;
  }


  public CoverageInfo defaultInterpolationMethod(String defaultInterpolationMethod) {
    
    this.defaultInterpolationMethod = defaultInterpolationMethod;
    return this;
  }

   /**
   * Default resampling (interpolation) method that will be used for this coverage.
   * @return defaultInterpolationMethod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Default resampling (interpolation) method that will be used for this coverage.")
  @JsonProperty(JSON_PROPERTY_DEFAULT_INTERPOLATION_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDefaultInterpolationMethod() {
    return defaultInterpolationMethod;
  }


  public void setDefaultInterpolationMethod(String defaultInterpolationMethod) {
    this.defaultInterpolationMethod = defaultInterpolationMethod;
  }


  public CoverageInfo interpolationMethods(List<String> interpolationMethods) {
    
    this.interpolationMethods = interpolationMethods;
    return this;
  }

  public CoverageInfo addInterpolationMethodsItem(String interpolationMethodsItem) {
    if (this.interpolationMethods == null) {
      this.interpolationMethods = new ArrayList<>();
    }
    this.interpolationMethods.add(interpolationMethodsItem);
    return this;
  }

   /**
   * available interporlations methods for this coverage
   * @return interpolationMethods
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "available interporlations methods for this coverage")
  @JsonProperty(JSON_PROPERTY_INTERPOLATION_METHODS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getInterpolationMethods() {
    return interpolationMethods;
  }


  public void setInterpolationMethods(List<String> interpolationMethods) {
    this.interpolationMethods = interpolationMethods;
  }


  public CoverageInfo parameters(Map<String, Object> parameters) {
    
    this.parameters = parameters;
    return this;
  }

  public CoverageInfo putParametersItem(String key, Object parametersItem) {
    if (this.parameters == null) {
      this.parameters = new HashMap<>();
    }
    this.parameters.put(key, parametersItem);
    return this;
  }

   /**
   * Get parameters
   * @return parameters
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getParameters() {
    return parameters;
  }


  public void setParameters(Map<String, Object> parameters) {
    this.parameters = parameters;
  }


  public CoverageInfo dimensions(List<CoverageDimensionInfo> dimensions) {
    
    this.dimensions = dimensions;
    return this;
  }

  public CoverageInfo addDimensionsItem(CoverageDimensionInfo dimensionsItem) {
    if (this.dimensions == null) {
      this.dimensions = new ArrayList<>();
    }
    this.dimensions.add(dimensionsItem);
    return this;
  }

   /**
   * raster dimensions
   * @return dimensions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "raster dimensions")
  @JsonProperty(JSON_PROPERTY_DIMENSIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CoverageDimensionInfo> getDimensions() {
    return dimensions;
  }


  public void setDimensions(List<CoverageDimensionInfo> dimensions) {
    this.dimensions = dimensions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CoverageInfo coverageInfo = (CoverageInfo) o;
    return Objects.equals(this.name, coverageInfo.name) &&
        Objects.equals(this.nativeName, coverageInfo.nativeName) &&
        Objects.equals(this.namespace, coverageInfo.namespace) &&
        Objects.equals(this.title, coverageInfo.title) &&
        Objects.equals(this._abstract, coverageInfo._abstract) &&
        Objects.equals(this.description, coverageInfo.description) &&
        Objects.equals(this.enabled, coverageInfo.enabled) &&
        Objects.equals(this.alias, coverageInfo.alias) &&
        Objects.equals(this.dataLinks, coverageInfo.dataLinks) &&
        Objects.equals(this.disabledServices, coverageInfo.disabledServices) &&
        Objects.equals(this.keywords, coverageInfo.keywords) &&
        Objects.equals(this.latLonBoundingBox, coverageInfo.latLonBoundingBox) &&
        Objects.equals(this.nativeBoundingBox, coverageInfo.nativeBoundingBox) &&
        Objects.equals(this.metadata, coverageInfo.metadata) &&
        Objects.equals(this.metadataLinks, coverageInfo.metadataLinks) &&
        Objects.equals(this.nativeCRS, coverageInfo.nativeCRS) &&
        Objects.equals(this.srs, coverageInfo.srs) &&
        Objects.equals(this.projectionPolicy, coverageInfo.projectionPolicy) &&
        Objects.equals(this.advertised, coverageInfo.advertised) &&
        Objects.equals(this.serviceConfiguration, coverageInfo.serviceConfiguration) &&
        Objects.equals(this.store, coverageInfo.store) &&
        Objects.equals(this.nativeCoverageName, coverageInfo.nativeCoverageName) &&
        Objects.equals(this.nativeFormat, coverageInfo.nativeFormat) &&
        Objects.equals(this.supportedFormats, coverageInfo.supportedFormats) &&
        Objects.equals(this.requestSRS, coverageInfo.requestSRS) &&
        Objects.equals(this.responseSRS, coverageInfo.responseSRS) &&
        Objects.equals(this.defaultInterpolationMethod, coverageInfo.defaultInterpolationMethod) &&
        Objects.equals(this.interpolationMethods, coverageInfo.interpolationMethods) &&
        Objects.equals(this.parameters, coverageInfo.parameters) &&
        Objects.equals(this.dimensions, coverageInfo.dimensions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, nativeName, namespace, title, _abstract, description, enabled, alias, dataLinks, disabledServices, keywords, latLonBoundingBox, nativeBoundingBox, metadata, metadataLinks, nativeCRS, srs, projectionPolicy, advertised, serviceConfiguration, store, nativeCoverageName, nativeFormat, supportedFormats, requestSRS, responseSRS, defaultInterpolationMethod, interpolationMethods, parameters, dimensions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CoverageInfo {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nativeName: ").append(toIndentedString(nativeName)).append("\n");
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    _abstract: ").append(toIndentedString(_abstract)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
    sb.append("    dataLinks: ").append(toIndentedString(dataLinks)).append("\n");
    sb.append("    disabledServices: ").append(toIndentedString(disabledServices)).append("\n");
    sb.append("    keywords: ").append(toIndentedString(keywords)).append("\n");
    sb.append("    latLonBoundingBox: ").append(toIndentedString(latLonBoundingBox)).append("\n");
    sb.append("    nativeBoundingBox: ").append(toIndentedString(nativeBoundingBox)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    metadataLinks: ").append(toIndentedString(metadataLinks)).append("\n");
    sb.append("    nativeCRS: ").append(toIndentedString(nativeCRS)).append("\n");
    sb.append("    srs: ").append(toIndentedString(srs)).append("\n");
    sb.append("    projectionPolicy: ").append(toIndentedString(projectionPolicy)).append("\n");
    sb.append("    advertised: ").append(toIndentedString(advertised)).append("\n");
    sb.append("    serviceConfiguration: ").append(toIndentedString(serviceConfiguration)).append("\n");
    sb.append("    store: ").append(toIndentedString(store)).append("\n");
    sb.append("    nativeCoverageName: ").append(toIndentedString(nativeCoverageName)).append("\n");
    sb.append("    nativeFormat: ").append(toIndentedString(nativeFormat)).append("\n");
    sb.append("    supportedFormats: ").append(toIndentedString(supportedFormats)).append("\n");
    sb.append("    requestSRS: ").append(toIndentedString(requestSRS)).append("\n");
    sb.append("    responseSRS: ").append(toIndentedString(responseSRS)).append("\n");
    sb.append("    defaultInterpolationMethod: ").append(toIndentedString(defaultInterpolationMethod)).append("\n");
    sb.append("    interpolationMethods: ").append(toIndentedString(interpolationMethods)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("    dimensions: ").append(toIndentedString(dimensions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

