/*
 * GeoServer Catalog Model
 * GeoServer Catalog Model Objects
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.geoserver.openapi.model.catalog;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.geoserver.openapi.model.catalog.WorkspaceInfo;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * CoverageStoreInfo
 */
@JsonPropertyOrder({
  CoverageStoreInfo.JSON_PROPERTY_NAME,
  CoverageStoreInfo.JSON_PROPERTY_DESCRIPTION,
  CoverageStoreInfo.JSON_PROPERTY_TYPE,
  CoverageStoreInfo.JSON_PROPERTY_ENABLED,
  CoverageStoreInfo.JSON_PROPERTY_URL,
  CoverageStoreInfo.JSON_PROPERTY_WORKSPACE
})

public class CoverageStoreInfo {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  /**
   * Type of coverage store
   */
  public enum TypeEnum {
    ARCGRID("ArcGrid"),
    
    GEOTIFF("GeoTIFF"),
    
    IMAGEMOSAIC("ImageMosaic"),
    
    WORLDIMAGE("WorldImage");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  private TypeEnum type;

  public static final String JSON_PROPERTY_ENABLED = "enabled";
  private Boolean enabled;

  public static final String JSON_PROPERTY_URL = "url";
  private String url;

  public static final String JSON_PROPERTY_WORKSPACE = "workspace";
  private WorkspaceInfo workspace;


  public CoverageStoreInfo name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name of the coverage store
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Name of the coverage store")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public CoverageStoreInfo description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Description of the coverage store
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Description of the coverage store")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public CoverageStoreInfo type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * Type of coverage store
   * @return type
  **/
  @ApiModelProperty(required = true, value = "Type of coverage store")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  public void setType(TypeEnum type) {
    this.type = type;
  }


  public CoverageStoreInfo enabled(Boolean enabled) {
    
    this.enabled = enabled;
    return this;
  }

   /**
   * Whether the store is enabled, or not
   * @return enabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether the store is enabled, or not")
  @JsonProperty(JSON_PROPERTY_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEnabled() {
    return enabled;
  }


  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }


  public CoverageStoreInfo url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * Location of the raster data source (often, but not necessarily, a file). Can be relative to the data directory.
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Location of the raster data source (often, but not necessarily, a file). Can be relative to the data directory.")
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  public CoverageStoreInfo workspace(WorkspaceInfo workspace) {
    
    this.workspace = workspace;
    return this;
  }

   /**
   * Get workspace
   * @return workspace
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WORKSPACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public WorkspaceInfo getWorkspace() {
    return workspace;
  }


  public void setWorkspace(WorkspaceInfo workspace) {
    this.workspace = workspace;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CoverageStoreInfo coverageStoreInfo = (CoverageStoreInfo) o;
    return Objects.equals(this.name, coverageStoreInfo.name) &&
        Objects.equals(this.description, coverageStoreInfo.description) &&
        Objects.equals(this.type, coverageStoreInfo.type) &&
        Objects.equals(this.enabled, coverageStoreInfo.enabled) &&
        Objects.equals(this.url, coverageStoreInfo.url) &&
        Objects.equals(this.workspace, coverageStoreInfo.workspace);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, type, enabled, url, workspace);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CoverageStoreInfo {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    workspace: ").append(toIndentedString(workspace)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

