/*
 * GeoServer Catalog Model
 * GeoServer Catalog Model Objects
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.geoserver.openapi.model.catalog;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * EnvelopeInfo
 */
@JsonPropertyOrder({
  EnvelopeInfo.JSON_PROPERTY_MINX,
  EnvelopeInfo.JSON_PROPERTY_MAXX,
  EnvelopeInfo.JSON_PROPERTY_MINY,
  EnvelopeInfo.JSON_PROPERTY_MAXY,
  EnvelopeInfo.JSON_PROPERTY_CRS
})

public class EnvelopeInfo {
  public static final String JSON_PROPERTY_MINX = "minx";
  private Double minx;

  public static final String JSON_PROPERTY_MAXX = "maxx";
  private Double maxx;

  public static final String JSON_PROPERTY_MINY = "miny";
  private Double miny;

  public static final String JSON_PROPERTY_MAXY = "maxy";
  private Double maxy;

  public static final String JSON_PROPERTY_CRS = "crs";
  private String crs;


  public EnvelopeInfo minx(Double minx) {
    
    this.minx = minx;
    return this;
  }

   /**
   * The min x coordinate
   * @return minx
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The min x coordinate")
  @JsonProperty(JSON_PROPERTY_MINX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getMinx() {
    return minx;
  }


  public void setMinx(Double minx) {
    this.minx = minx;
  }


  public EnvelopeInfo maxx(Double maxx) {
    
    this.maxx = maxx;
    return this;
  }

   /**
   * The max x coordinate
   * @return maxx
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The max x coordinate")
  @JsonProperty(JSON_PROPERTY_MAXX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getMaxx() {
    return maxx;
  }


  public void setMaxx(Double maxx) {
    this.maxx = maxx;
  }


  public EnvelopeInfo miny(Double miny) {
    
    this.miny = miny;
    return this;
  }

   /**
   * The min y coordinate
   * @return miny
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The min y coordinate")
  @JsonProperty(JSON_PROPERTY_MINY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getMiny() {
    return miny;
  }


  public void setMiny(Double miny) {
    this.miny = miny;
  }


  public EnvelopeInfo maxy(Double maxy) {
    
    this.maxy = maxy;
    return this;
  }

   /**
   * The max y coordinate
   * @return maxy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The max y coordinate")
  @JsonProperty(JSON_PROPERTY_MAXY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getMaxy() {
    return maxy;
  }


  public void setMaxy(Double maxy) {
    this.maxy = maxy;
  }


  public EnvelopeInfo crs(String crs) {
    
    this.crs = crs;
    return this;
  }

   /**
   * The coordinate reference system object of the bounding box.
   * @return crs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The coordinate reference system object of the bounding box.")
  @JsonProperty(JSON_PROPERTY_CRS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCrs() {
    return crs;
  }


  public void setCrs(String crs) {
    this.crs = crs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnvelopeInfo envelopeInfo = (EnvelopeInfo) o;
    return Objects.equals(this.minx, envelopeInfo.minx) &&
        Objects.equals(this.maxx, envelopeInfo.maxx) &&
        Objects.equals(this.miny, envelopeInfo.miny) &&
        Objects.equals(this.maxy, envelopeInfo.maxy) &&
        Objects.equals(this.crs, envelopeInfo.crs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(minx, maxx, miny, maxy, crs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnvelopeInfo {\n");
    sb.append("    minx: ").append(toIndentedString(minx)).append("\n");
    sb.append("    maxx: ").append(toIndentedString(maxx)).append("\n");
    sb.append("    miny: ").append(toIndentedString(miny)).append("\n");
    sb.append("    maxy: ").append(toIndentedString(maxy)).append("\n");
    sb.append("    crs: ").append(toIndentedString(crs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

