/*
 * GeoServer Catalog Model
 * GeoServer Catalog Model Objects
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.geoserver.openapi.model.catalog;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * LayerIdentifierInfo
 */
@JsonPropertyOrder({
  LayerIdentifierInfo.JSON_PROPERTY_AUTHORITY,
  LayerIdentifierInfo.JSON_PROPERTY_IDENTIFIER
})

public class LayerIdentifierInfo {
  public static final String JSON_PROPERTY_AUTHORITY = "authority";
  private String authority;

  public static final String JSON_PROPERTY_IDENTIFIER = "identifier";
  private String identifier;


  public LayerIdentifierInfo authority(String authority) {
    
    this.authority = authority;
    return this;
  }

   /**
   * Authority cited, for details see authorityURLs
   * @return authority
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Authority cited, for details see authorityURLs")
  @JsonProperty(JSON_PROPERTY_AUTHORITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAuthority() {
    return authority;
  }


  public void setAuthority(String authority) {
    this.authority = authority;
  }


  public LayerIdentifierInfo identifier(String identifier) {
    
    this.identifier = identifier;
    return this;
  }

   /**
   * Work citied, often a data standard provided by
   * @return identifier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Work citied, often a data standard provided by")
  @JsonProperty(JSON_PROPERTY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIdentifier() {
    return identifier;
  }


  public void setIdentifier(String identifier) {
    this.identifier = identifier;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LayerIdentifierInfo layerIdentifierInfo = (LayerIdentifierInfo) o;
    return Objects.equals(this.authority, layerIdentifierInfo.authority) &&
        Objects.equals(this.identifier, layerIdentifierInfo.identifier);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authority, identifier);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LayerIdentifierInfo {\n");
    sb.append("    authority: ").append(toIndentedString(authority)).append("\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

