/*
 * GeoServer Config Model
 * GeoServer Config Model Objects
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.geoserver.openapi.model.config;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * A set of mime types allowed for a getMap request. Active if getMapMimeTypeCheckingEnabled is true
 */
@ApiModel(description = "A set of mime types allowed for a getMap request. Active if getMapMimeTypeCheckingEnabled is true")
@JsonPropertyOrder({
  GetMapMimeTypes.JSON_PROPERTY_STRING
})

public class GetMapMimeTypes {
  public static final String JSON_PROPERTY_STRING = "string";
  private List<String> string = null;


  public GetMapMimeTypes string(List<String> string) {
    
    this.string = string;
    return this;
  }

  public GetMapMimeTypes addStringItem(String stringItem) {
    if (this.string == null) {
      this.string = new ArrayList<>();
    }
    this.string.add(stringItem);
    return this;
  }

   /**
   * Get string
   * @return string
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getString() {
    return string;
  }


  public void setString(List<String> string) {
    this.string = string;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetMapMimeTypes getMapMimeTypes = (GetMapMimeTypes) o;
    return Objects.equals(this.string, getMapMimeTypes.string);
  }

  @Override
  public int hashCode() {
    return Objects.hash(string);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetMapMimeTypes {\n");
    sb.append("    string: ").append(toIndentedString(string)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

