/*
 * GeoServer Config Model
 * GeoServer Config Model Objects
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.geoserver.openapi.model.config;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ServiceInfo
 */
@JsonPropertyOrder({
  ServiceInfo.JSON_PROPERTY_WORKSPACE,
  ServiceInfo.JSON_PROPERTY_ENABLED,
  ServiceInfo.JSON_PROPERTY_NAME,
  ServiceInfo.JSON_PROPERTY_TITLE,
  ServiceInfo.JSON_PROPERTY_ABSTRCT,
  ServiceInfo.JSON_PROPERTY_MAINTAINER,
  ServiceInfo.JSON_PROPERTY_ACCESS_CONSTRAINTS,
  ServiceInfo.JSON_PROPERTY_FEES,
  ServiceInfo.JSON_PROPERTY_EXCEPTION_FORMATS,
  ServiceInfo.JSON_PROPERTY_CITE_COMPLIANT,
  ServiceInfo.JSON_PROPERTY_ONLINE_RESOURCE,
  ServiceInfo.JSON_PROPERTY_SCHEMA_BASE_U_R_L,
  ServiceInfo.JSON_PROPERTY_OUTPUT_STRATEGY,
  ServiceInfo.JSON_PROPERTY_VERBOSE
})

public class ServiceInfo {
  public static final String JSON_PROPERTY_WORKSPACE = "workspace";
  private org.geoserver.openapi.model.catalog.WorkspaceInfo workspace;

  public static final String JSON_PROPERTY_ENABLED = "enabled";
  private Boolean enabled;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_TITLE = "title";
  private String title;

  public static final String JSON_PROPERTY_ABSTRCT = "abstrct";
  private String abstrct;

  public static final String JSON_PROPERTY_MAINTAINER = "maintainer";
  private String maintainer;

  public static final String JSON_PROPERTY_ACCESS_CONSTRAINTS = "accessConstraints";
  private String accessConstraints;

  public static final String JSON_PROPERTY_FEES = "fees";
  private String fees;

  public static final String JSON_PROPERTY_EXCEPTION_FORMATS = "exceptionFormats";
  private List<String> exceptionFormats = null;

  public static final String JSON_PROPERTY_CITE_COMPLIANT = "citeCompliant";
  private Boolean citeCompliant;

  public static final String JSON_PROPERTY_ONLINE_RESOURCE = "onlineResource";
  private String onlineResource;

  public static final String JSON_PROPERTY_SCHEMA_BASE_U_R_L = "schemaBaseURL";
  private String schemaBaseURL;

  public static final String JSON_PROPERTY_OUTPUT_STRATEGY = "outputStrategy";
  private String outputStrategy;

  public static final String JSON_PROPERTY_VERBOSE = "verbose";
  private Boolean verbose;


  public ServiceInfo workspace(org.geoserver.openapi.model.catalog.WorkspaceInfo workspace) {
    
    this.workspace = workspace;
    return this;
  }

   /**
   * Get workspace
   * @return workspace
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WORKSPACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public org.geoserver.openapi.model.catalog.WorkspaceInfo getWorkspace() {
    return workspace;
  }


  public void setWorkspace(org.geoserver.openapi.model.catalog.WorkspaceInfo workspace) {
    this.workspace = workspace;
  }


  public ServiceInfo enabled(Boolean enabled) {
    
    this.enabled = enabled;
    return this;
  }

   /**
   * Status of the service
   * @return enabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Status of the service")
  @JsonProperty(JSON_PROPERTY_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEnabled() {
    return enabled;
  }


  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }


  public ServiceInfo name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name of the service. This value is unique among all instances of ServiceInfo and can be used as an identifier.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name of the service. This value is unique among all instances of ServiceInfo and can be used as an identifier.")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public ServiceInfo title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Title of the service
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Title of the service")
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public ServiceInfo abstrct(String abstrct) {
    
    this.abstrct = abstrct;
    return this;
  }

   /**
   * description of the service
   * @return abstrct
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "description of the service")
  @JsonProperty(JSON_PROPERTY_ABSTRCT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAbstrct() {
    return abstrct;
  }


  public void setAbstrct(String abstrct) {
    this.abstrct = abstrct;
  }


  public ServiceInfo maintainer(String maintainer) {
    
    this.maintainer = maintainer;
    return this;
  }

   /**
   * maintainer of the service
   * @return maintainer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "maintainer of the service")
  @JsonProperty(JSON_PROPERTY_MAINTAINER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMaintainer() {
    return maintainer;
  }


  public void setMaintainer(String maintainer) {
    this.maintainer = maintainer;
  }


  public ServiceInfo accessConstraints(String accessConstraints) {
    
    this.accessConstraints = accessConstraints;
    return this;
  }

   /**
   * Get accessConstraints
   * @return accessConstraints
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ACCESS_CONSTRAINTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccessConstraints() {
    return accessConstraints;
  }


  public void setAccessConstraints(String accessConstraints) {
    this.accessConstraints = accessConstraints;
  }


  public ServiceInfo fees(String fees) {
    
    this.fees = fees;
    return this;
  }

   /**
   * Get fees
   * @return fees
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FEES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFees() {
    return fees;
  }


  public void setFees(String fees) {
    this.fees = fees;
  }


  public ServiceInfo exceptionFormats(List<String> exceptionFormats) {
    
    this.exceptionFormats = exceptionFormats;
    return this;
  }

  public ServiceInfo addExceptionFormatsItem(String exceptionFormatsItem) {
    if (this.exceptionFormats == null) {
      this.exceptionFormats = new ArrayList<>();
    }
    this.exceptionFormats.add(exceptionFormatsItem);
    return this;
  }

   /**
   * Exception formats the service can provide.
   * @return exceptionFormats
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Exception formats the service can provide.")
  @JsonProperty(JSON_PROPERTY_EXCEPTION_FORMATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getExceptionFormats() {
    return exceptionFormats;
  }


  public void setExceptionFormats(List<String> exceptionFormats) {
    this.exceptionFormats = exceptionFormats;
  }


  public ServiceInfo citeCompliant(Boolean citeCompliant) {
    
    this.citeCompliant = citeCompliant;
    return this;
  }

   /**
   * Status of service CITE compliance.
   * @return citeCompliant
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Status of service CITE compliance.")
  @JsonProperty(JSON_PROPERTY_CITE_COMPLIANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCiteCompliant() {
    return citeCompliant;
  }


  public void setCiteCompliant(Boolean citeCompliant) {
    this.citeCompliant = citeCompliant;
  }


  public ServiceInfo onlineResource(String onlineResource) {
    
    this.onlineResource = onlineResource;
    return this;
  }

   /**
   * Get onlineResource
   * @return onlineResource
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ONLINE_RESOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOnlineResource() {
    return onlineResource;
  }


  public void setOnlineResource(String onlineResource) {
    this.onlineResource = onlineResource;
  }


  public ServiceInfo schemaBaseURL(String schemaBaseURL) {
    
    this.schemaBaseURL = schemaBaseURL;
    return this;
  }

   /**
   * The base url for the schemas describing the service.
   * @return schemaBaseURL
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The base url for the schemas describing the service.")
  @JsonProperty(JSON_PROPERTY_SCHEMA_BASE_U_R_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSchemaBaseURL() {
    return schemaBaseURL;
  }


  public void setSchemaBaseURL(String schemaBaseURL) {
    this.schemaBaseURL = schemaBaseURL;
  }


  public ServiceInfo outputStrategy(String outputStrategy) {
    
    this.outputStrategy = outputStrategy;
    return this;
  }

   /**
   * This value is an identifier which indicates how the output of a response should behave. An example might be \&quot;performance\&quot;, indicating that the response should be encoded as quickly as possible.
   * @return outputStrategy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "This value is an identifier which indicates how the output of a response should behave. An example might be \"performance\", indicating that the response should be encoded as quickly as possible.")
  @JsonProperty(JSON_PROPERTY_OUTPUT_STRATEGY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOutputStrategy() {
    return outputStrategy;
  }


  public void setOutputStrategy(String outputStrategy) {
    this.outputStrategy = outputStrategy;
  }


  public ServiceInfo verbose(Boolean verbose) {
    
    this.verbose = verbose;
    return this;
  }

   /**
   * Flag indicating if the service should be verbose or not.
   * @return verbose
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Flag indicating if the service should be verbose or not.")
  @JsonProperty(JSON_PROPERTY_VERBOSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getVerbose() {
    return verbose;
  }


  public void setVerbose(Boolean verbose) {
    this.verbose = verbose;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceInfo serviceInfo = (ServiceInfo) o;
    return Objects.equals(this.workspace, serviceInfo.workspace) &&
        Objects.equals(this.enabled, serviceInfo.enabled) &&
        Objects.equals(this.name, serviceInfo.name) &&
        Objects.equals(this.title, serviceInfo.title) &&
        Objects.equals(this.abstrct, serviceInfo.abstrct) &&
        Objects.equals(this.maintainer, serviceInfo.maintainer) &&
        Objects.equals(this.accessConstraints, serviceInfo.accessConstraints) &&
        Objects.equals(this.fees, serviceInfo.fees) &&
        Objects.equals(this.exceptionFormats, serviceInfo.exceptionFormats) &&
        Objects.equals(this.citeCompliant, serviceInfo.citeCompliant) &&
        Objects.equals(this.onlineResource, serviceInfo.onlineResource) &&
        Objects.equals(this.schemaBaseURL, serviceInfo.schemaBaseURL) &&
        Objects.equals(this.outputStrategy, serviceInfo.outputStrategy) &&
        Objects.equals(this.verbose, serviceInfo.verbose);
  }

  @Override
  public int hashCode() {
    return Objects.hash(workspace, enabled, name, title, abstrct, maintainer, accessConstraints, fees, exceptionFormats, citeCompliant, onlineResource, schemaBaseURL, outputStrategy, verbose);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceInfo {\n");
    sb.append("    workspace: ").append(toIndentedString(workspace)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    abstrct: ").append(toIndentedString(abstrct)).append("\n");
    sb.append("    maintainer: ").append(toIndentedString(maintainer)).append("\n");
    sb.append("    accessConstraints: ").append(toIndentedString(accessConstraints)).append("\n");
    sb.append("    fees: ").append(toIndentedString(fees)).append("\n");
    sb.append("    exceptionFormats: ").append(toIndentedString(exceptionFormats)).append("\n");
    sb.append("    citeCompliant: ").append(toIndentedString(citeCompliant)).append("\n");
    sb.append("    onlineResource: ").append(toIndentedString(onlineResource)).append("\n");
    sb.append("    schemaBaseURL: ").append(toIndentedString(schemaBaseURL)).append("\n");
    sb.append("    outputStrategy: ").append(toIndentedString(outputStrategy)).append("\n");
    sb.append("    verbose: ").append(toIndentedString(verbose)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

