/*
 * GeoServer Config Model
 * GeoServer Config Model Objects
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.geoserver.openapi.model.config;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * WCSInfoAllOf
 */
@JsonPropertyOrder({
  WCSInfoAllOf.JSON_PROPERTY_GML_PREFIXING,
  WCSInfoAllOf.JSON_PROPERTY_LAT_LON,
  WCSInfoAllOf.JSON_PROPERTY_MAX_INPUT_MEMORY,
  WCSInfoAllOf.JSON_PROPERTY_MAX_OUTPUT_MEMORY
})

public class WCSInfoAllOf {
  public static final String JSON_PROPERTY_GML_PREFIXING = "gmlPrefixing";
  private Boolean gmlPrefixing;

  public static final String JSON_PROPERTY_LAT_LON = "latLon";
  private Boolean latLon;

  public static final String JSON_PROPERTY_MAX_INPUT_MEMORY = "maxInputMemory";
  private Boolean maxInputMemory;

  public static final String JSON_PROPERTY_MAX_OUTPUT_MEMORY = "maxOutputMemory";
  private Boolean maxOutputMemory;


  public WCSInfoAllOf gmlPrefixing(Boolean gmlPrefixing) {
    
    this.gmlPrefixing = gmlPrefixing;
    return this;
  }

   /**
   * Get gmlPrefixing
   * @return gmlPrefixing
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GML_PREFIXING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getGmlPrefixing() {
    return gmlPrefixing;
  }


  public void setGmlPrefixing(Boolean gmlPrefixing) {
    this.gmlPrefixing = gmlPrefixing;
  }


  public WCSInfoAllOf latLon(Boolean latLon) {
    
    this.latLon = latLon;
    return this;
  }

   /**
   * Get latLon
   * @return latLon
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LAT_LON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getLatLon() {
    return latLon;
  }


  public void setLatLon(Boolean latLon) {
    this.latLon = latLon;
  }


  public WCSInfoAllOf maxInputMemory(Boolean maxInputMemory) {
    
    this.maxInputMemory = maxInputMemory;
    return this;
  }

   /**
   * Get maxInputMemory
   * @return maxInputMemory
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MAX_INPUT_MEMORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getMaxInputMemory() {
    return maxInputMemory;
  }


  public void setMaxInputMemory(Boolean maxInputMemory) {
    this.maxInputMemory = maxInputMemory;
  }


  public WCSInfoAllOf maxOutputMemory(Boolean maxOutputMemory) {
    
    this.maxOutputMemory = maxOutputMemory;
    return this;
  }

   /**
   * Get maxOutputMemory
   * @return maxOutputMemory
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MAX_OUTPUT_MEMORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getMaxOutputMemory() {
    return maxOutputMemory;
  }


  public void setMaxOutputMemory(Boolean maxOutputMemory) {
    this.maxOutputMemory = maxOutputMemory;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WCSInfoAllOf wcSInfoAllOf = (WCSInfoAllOf) o;
    return Objects.equals(this.gmlPrefixing, wcSInfoAllOf.gmlPrefixing) &&
        Objects.equals(this.latLon, wcSInfoAllOf.latLon) &&
        Objects.equals(this.maxInputMemory, wcSInfoAllOf.maxInputMemory) &&
        Objects.equals(this.maxOutputMemory, wcSInfoAllOf.maxOutputMemory);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gmlPrefixing, latLon, maxInputMemory, maxOutputMemory);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WCSInfoAllOf {\n");
    sb.append("    gmlPrefixing: ").append(toIndentedString(gmlPrefixing)).append("\n");
    sb.append("    latLon: ").append(toIndentedString(latLon)).append("\n");
    sb.append("    maxInputMemory: ").append(toIndentedString(maxInputMemory)).append("\n");
    sb.append("    maxOutputMemory: ").append(toIndentedString(maxOutputMemory)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

