/*
 * GeoServer Config Model
 * GeoServer Config Model Objects
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.geoserver.openapi.model.config;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.geoserver.openapi.model.config.ServiceInfo;
import org.geoserver.openapi.model.config.WFSInfoAllOf;
import org.geoserver.openapi.model.config.WFSInfoGmlSettings;
import org.geoserver.openapi.model.config.WFSServiceLevel;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * WFSInfo
 */
@JsonPropertyOrder({
  WFSInfo.JSON_PROPERTY_WORKSPACE,
  WFSInfo.JSON_PROPERTY_ENABLED,
  WFSInfo.JSON_PROPERTY_NAME,
  WFSInfo.JSON_PROPERTY_TITLE,
  WFSInfo.JSON_PROPERTY_ABSTRCT,
  WFSInfo.JSON_PROPERTY_MAINTAINER,
  WFSInfo.JSON_PROPERTY_ACCESS_CONSTRAINTS,
  WFSInfo.JSON_PROPERTY_FEES,
  WFSInfo.JSON_PROPERTY_EXCEPTION_FORMATS,
  WFSInfo.JSON_PROPERTY_CITE_COMPLIANT,
  WFSInfo.JSON_PROPERTY_ONLINE_RESOURCE,
  WFSInfo.JSON_PROPERTY_SCHEMA_BASE_U_R_L,
  WFSInfo.JSON_PROPERTY_OUTPUT_STRATEGY,
  WFSInfo.JSON_PROPERTY_VERBOSE,
  WFSInfo.JSON_PROPERTY_GML,
  WFSInfo.JSON_PROPERTY_SERVICE_LEVEL,
  WFSInfo.JSON_PROPERTY_MAX_FEATURES,
  WFSInfo.JSON_PROPERTY_FEATURE_BOUNDING,
  WFSInfo.JSON_PROPERTY_CANONICAL_SCHEMA_LOCATION,
  WFSInfo.JSON_PROPERTY_ENCODE_FEATURE_MEMBER,
  WFSInfo.JSON_PROPERTY_HITS_IGNORE_MAX_FEATURES,
  WFSInfo.JSON_PROPERTY_GET_FEATURE_OUTPUT_TYPE_CHECKING_ENABLED,
  WFSInfo.JSON_PROPERTY_GET_FEATURE_OUTPUT_TYPES
})

public class WFSInfo {
  public static final String JSON_PROPERTY_WORKSPACE = "workspace";
  private org.geoserver.openapi.model.catalog.WorkspaceInfo workspace;

  public static final String JSON_PROPERTY_ENABLED = "enabled";
  private Boolean enabled;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_TITLE = "title";
  private String title;

  public static final String JSON_PROPERTY_ABSTRCT = "abstrct";
  private String abstrct;

  public static final String JSON_PROPERTY_MAINTAINER = "maintainer";
  private String maintainer;

  public static final String JSON_PROPERTY_ACCESS_CONSTRAINTS = "accessConstraints";
  private String accessConstraints;

  public static final String JSON_PROPERTY_FEES = "fees";
  private String fees;

  public static final String JSON_PROPERTY_EXCEPTION_FORMATS = "exceptionFormats";
  private List<String> exceptionFormats = null;

  public static final String JSON_PROPERTY_CITE_COMPLIANT = "citeCompliant";
  private Boolean citeCompliant;

  public static final String JSON_PROPERTY_ONLINE_RESOURCE = "onlineResource";
  private String onlineResource;

  public static final String JSON_PROPERTY_SCHEMA_BASE_U_R_L = "schemaBaseURL";
  private String schemaBaseURL;

  public static final String JSON_PROPERTY_OUTPUT_STRATEGY = "outputStrategy";
  private String outputStrategy;

  public static final String JSON_PROPERTY_VERBOSE = "verbose";
  private Boolean verbose;

  public static final String JSON_PROPERTY_GML = "gml";
  private WFSInfoGmlSettings gml;

  public static final String JSON_PROPERTY_SERVICE_LEVEL = "serviceLevel";
  private WFSServiceLevel serviceLevel;

  public static final String JSON_PROPERTY_MAX_FEATURES = "maxFeatures";
  private Integer maxFeatures;

  public static final String JSON_PROPERTY_FEATURE_BOUNDING = "featureBounding";
  private Boolean featureBounding;

  public static final String JSON_PROPERTY_CANONICAL_SCHEMA_LOCATION = "canonicalSchemaLocation";
  private Boolean canonicalSchemaLocation;

  public static final String JSON_PROPERTY_ENCODE_FEATURE_MEMBER = "encodeFeatureMember";
  private Boolean encodeFeatureMember;

  public static final String JSON_PROPERTY_HITS_IGNORE_MAX_FEATURES = "hitsIgnoreMaxFeatures";
  private Boolean hitsIgnoreMaxFeatures;

  public static final String JSON_PROPERTY_GET_FEATURE_OUTPUT_TYPE_CHECKING_ENABLED = "getFeatureOutputTypeCheckingEnabled";
  private Boolean getFeatureOutputTypeCheckingEnabled;

  public static final String JSON_PROPERTY_GET_FEATURE_OUTPUT_TYPES = "getFeatureOutputTypes";
  private List<String> getFeatureOutputTypes = null;


  public WFSInfo workspace(org.geoserver.openapi.model.catalog.WorkspaceInfo workspace) {
    
    this.workspace = workspace;
    return this;
  }

   /**
   * Get workspace
   * @return workspace
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WORKSPACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public org.geoserver.openapi.model.catalog.WorkspaceInfo getWorkspace() {
    return workspace;
  }


  public void setWorkspace(org.geoserver.openapi.model.catalog.WorkspaceInfo workspace) {
    this.workspace = workspace;
  }


  public WFSInfo enabled(Boolean enabled) {
    
    this.enabled = enabled;
    return this;
  }

   /**
   * Status of the service
   * @return enabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Status of the service")
  @JsonProperty(JSON_PROPERTY_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEnabled() {
    return enabled;
  }


  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }


  public WFSInfo name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name of the service. This value is unique among all instances of ServiceInfo and can be used as an identifier.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name of the service. This value is unique among all instances of ServiceInfo and can be used as an identifier.")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public WFSInfo title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Title of the service
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Title of the service")
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public WFSInfo abstrct(String abstrct) {
    
    this.abstrct = abstrct;
    return this;
  }

   /**
   * description of the service
   * @return abstrct
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "description of the service")
  @JsonProperty(JSON_PROPERTY_ABSTRCT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAbstrct() {
    return abstrct;
  }


  public void setAbstrct(String abstrct) {
    this.abstrct = abstrct;
  }


  public WFSInfo maintainer(String maintainer) {
    
    this.maintainer = maintainer;
    return this;
  }

   /**
   * maintainer of the service
   * @return maintainer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "maintainer of the service")
  @JsonProperty(JSON_PROPERTY_MAINTAINER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMaintainer() {
    return maintainer;
  }


  public void setMaintainer(String maintainer) {
    this.maintainer = maintainer;
  }


  public WFSInfo accessConstraints(String accessConstraints) {
    
    this.accessConstraints = accessConstraints;
    return this;
  }

   /**
   * Get accessConstraints
   * @return accessConstraints
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ACCESS_CONSTRAINTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccessConstraints() {
    return accessConstraints;
  }


  public void setAccessConstraints(String accessConstraints) {
    this.accessConstraints = accessConstraints;
  }


  public WFSInfo fees(String fees) {
    
    this.fees = fees;
    return this;
  }

   /**
   * Get fees
   * @return fees
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FEES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFees() {
    return fees;
  }


  public void setFees(String fees) {
    this.fees = fees;
  }


  public WFSInfo exceptionFormats(List<String> exceptionFormats) {
    
    this.exceptionFormats = exceptionFormats;
    return this;
  }

  public WFSInfo addExceptionFormatsItem(String exceptionFormatsItem) {
    if (this.exceptionFormats == null) {
      this.exceptionFormats = new ArrayList<>();
    }
    this.exceptionFormats.add(exceptionFormatsItem);
    return this;
  }

   /**
   * Exception formats the service can provide.
   * @return exceptionFormats
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Exception formats the service can provide.")
  @JsonProperty(JSON_PROPERTY_EXCEPTION_FORMATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getExceptionFormats() {
    return exceptionFormats;
  }


  public void setExceptionFormats(List<String> exceptionFormats) {
    this.exceptionFormats = exceptionFormats;
  }


  public WFSInfo citeCompliant(Boolean citeCompliant) {
    
    this.citeCompliant = citeCompliant;
    return this;
  }

   /**
   * Status of service CITE compliance.
   * @return citeCompliant
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Status of service CITE compliance.")
  @JsonProperty(JSON_PROPERTY_CITE_COMPLIANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCiteCompliant() {
    return citeCompliant;
  }


  public void setCiteCompliant(Boolean citeCompliant) {
    this.citeCompliant = citeCompliant;
  }


  public WFSInfo onlineResource(String onlineResource) {
    
    this.onlineResource = onlineResource;
    return this;
  }

   /**
   * Get onlineResource
   * @return onlineResource
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ONLINE_RESOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOnlineResource() {
    return onlineResource;
  }


  public void setOnlineResource(String onlineResource) {
    this.onlineResource = onlineResource;
  }


  public WFSInfo schemaBaseURL(String schemaBaseURL) {
    
    this.schemaBaseURL = schemaBaseURL;
    return this;
  }

   /**
   * The base url for the schemas describing the service.
   * @return schemaBaseURL
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The base url for the schemas describing the service.")
  @JsonProperty(JSON_PROPERTY_SCHEMA_BASE_U_R_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSchemaBaseURL() {
    return schemaBaseURL;
  }


  public void setSchemaBaseURL(String schemaBaseURL) {
    this.schemaBaseURL = schemaBaseURL;
  }


  public WFSInfo outputStrategy(String outputStrategy) {
    
    this.outputStrategy = outputStrategy;
    return this;
  }

   /**
   * This value is an identifier which indicates how the output of a response should behave. An example might be \&quot;performance\&quot;, indicating that the response should be encoded as quickly as possible.
   * @return outputStrategy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "This value is an identifier which indicates how the output of a response should behave. An example might be \"performance\", indicating that the response should be encoded as quickly as possible.")
  @JsonProperty(JSON_PROPERTY_OUTPUT_STRATEGY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOutputStrategy() {
    return outputStrategy;
  }


  public void setOutputStrategy(String outputStrategy) {
    this.outputStrategy = outputStrategy;
  }


  public WFSInfo verbose(Boolean verbose) {
    
    this.verbose = verbose;
    return this;
  }

   /**
   * Flag indicating if the service should be verbose or not.
   * @return verbose
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Flag indicating if the service should be verbose or not.")
  @JsonProperty(JSON_PROPERTY_VERBOSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getVerbose() {
    return verbose;
  }


  public void setVerbose(Boolean verbose) {
    this.verbose = verbose;
  }


  public WFSInfo gml(WFSInfoGmlSettings gml) {
    
    this.gml = gml;
    return this;
  }

   /**
   * Get gml
   * @return gml
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GML)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public WFSInfoGmlSettings getGml() {
    return gml;
  }


  public void setGml(WFSInfoGmlSettings gml) {
    this.gml = gml;
  }


  public WFSInfo serviceLevel(WFSServiceLevel serviceLevel) {
    
    this.serviceLevel = serviceLevel;
    return this;
  }

   /**
   * Get serviceLevel
   * @return serviceLevel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SERVICE_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public WFSServiceLevel getServiceLevel() {
    return serviceLevel;
  }


  public void setServiceLevel(WFSServiceLevel serviceLevel) {
    this.serviceLevel = serviceLevel;
  }


  public WFSInfo maxFeatures(Integer maxFeatures) {
    
    this.maxFeatures = maxFeatures;
    return this;
  }

   /**
   * Global cap on the number of features to allow when processing a request
   * @return maxFeatures
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Global cap on the number of features to allow when processing a request")
  @JsonProperty(JSON_PROPERTY_MAX_FEATURES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaxFeatures() {
    return maxFeatures;
  }


  public void setMaxFeatures(Integer maxFeatures) {
    this.maxFeatures = maxFeatures;
  }


  public WFSInfo featureBounding(Boolean featureBounding) {
    
    this.featureBounding = featureBounding;
    return this;
  }

   /**
   * Flag which determines if gml:bounds elements should be encoded at the feature level in GML output
   * @return featureBounding
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Flag which determines if gml:bounds elements should be encoded at the feature level in GML output")
  @JsonProperty(JSON_PROPERTY_FEATURE_BOUNDING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getFeatureBounding() {
    return featureBounding;
  }


  public void setFeatureBounding(Boolean featureBounding) {
    this.featureBounding = featureBounding;
  }


  public WFSInfo canonicalSchemaLocation(Boolean canonicalSchemaLocation) {
    
    this.canonicalSchemaLocation = canonicalSchemaLocation;
    return this;
  }

   /**
   * Flag that determines the encoding of the WFS schemaLocation. True if the WFS schemaLocation should refer to the canonical location, false if the WFS schemaLocation should refer to a copy served by GeoServer.
   * @return canonicalSchemaLocation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Flag that determines the encoding of the WFS schemaLocation. True if the WFS schemaLocation should refer to the canonical location, false if the WFS schemaLocation should refer to a copy served by GeoServer.")
  @JsonProperty(JSON_PROPERTY_CANONICAL_SCHEMA_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCanonicalSchemaLocation() {
    return canonicalSchemaLocation;
  }


  public void setCanonicalSchemaLocation(Boolean canonicalSchemaLocation) {
    this.canonicalSchemaLocation = canonicalSchemaLocation;
  }


  public WFSInfo encodeFeatureMember(Boolean encodeFeatureMember) {
    
    this.encodeFeatureMember = encodeFeatureMember;
    return this;
  }

   /**
   * Flag that determines encoding of featureMember or featureMembers. True if the featureMember should be encoded False if the featureMembers should be encoded.
   * @return encodeFeatureMember
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Flag that determines encoding of featureMember or featureMembers. True if the featureMember should be encoded False if the featureMembers should be encoded.")
  @JsonProperty(JSON_PROPERTY_ENCODE_FEATURE_MEMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEncodeFeatureMember() {
    return encodeFeatureMember;
  }


  public void setEncodeFeatureMember(Boolean encodeFeatureMember) {
    this.encodeFeatureMember = encodeFeatureMember;
  }


  public WFSInfo hitsIgnoreMaxFeatures(Boolean hitsIgnoreMaxFeatures) {
    
    this.hitsIgnoreMaxFeatures = hitsIgnoreMaxFeatures;
    return this;
  }

   /**
   * Flag that determines if WFS hit requests (counts) will ignore the maximum features limit for this server
   * @return hitsIgnoreMaxFeatures
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Flag that determines if WFS hit requests (counts) will ignore the maximum features limit for this server")
  @JsonProperty(JSON_PROPERTY_HITS_IGNORE_MAX_FEATURES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHitsIgnoreMaxFeatures() {
    return hitsIgnoreMaxFeatures;
  }


  public void setHitsIgnoreMaxFeatures(Boolean hitsIgnoreMaxFeatures) {
    this.hitsIgnoreMaxFeatures = hitsIgnoreMaxFeatures;
  }


  public WFSInfo getFeatureOutputTypeCheckingEnabled(Boolean getFeatureOutputTypeCheckingEnabled) {
    
    this.getFeatureOutputTypeCheckingEnabled = getFeatureOutputTypeCheckingEnabled;
    return this;
  }

   /**
   * Flag that determines if WFS GetFeature output type checking is enabled
   * @return getFeatureOutputTypeCheckingEnabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Flag that determines if WFS GetFeature output type checking is enabled")
  @JsonProperty(JSON_PROPERTY_GET_FEATURE_OUTPUT_TYPE_CHECKING_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getGetFeatureOutputTypeCheckingEnabled() {
    return getFeatureOutputTypeCheckingEnabled;
  }


  public void setGetFeatureOutputTypeCheckingEnabled(Boolean getFeatureOutputTypeCheckingEnabled) {
    this.getFeatureOutputTypeCheckingEnabled = getFeatureOutputTypeCheckingEnabled;
  }


  public WFSInfo getFeatureOutputTypes(List<String> getFeatureOutputTypes) {
    
    this.getFeatureOutputTypes = getFeatureOutputTypes;
    return this;
  }

  public WFSInfo addGetFeatureOutputTypesItem(String getFeatureOutputTypesItem) {
    if (this.getFeatureOutputTypes == null) {
      this.getFeatureOutputTypes = new ArrayList<>();
    }
    this.getFeatureOutputTypes.add(getFeatureOutputTypesItem);
    return this;
  }

   /**
   * A set of output types allowed for a getFeature request. Active if getFeatureOutputTypeCheckingEnabled is true
   * @return getFeatureOutputTypes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A set of output types allowed for a getFeature request. Active if getFeatureOutputTypeCheckingEnabled is true")
  @JsonProperty(JSON_PROPERTY_GET_FEATURE_OUTPUT_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getGetFeatureOutputTypes() {
    return getFeatureOutputTypes;
  }


  public void setGetFeatureOutputTypes(List<String> getFeatureOutputTypes) {
    this.getFeatureOutputTypes = getFeatureOutputTypes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WFSInfo wfSInfo = (WFSInfo) o;
    return Objects.equals(this.workspace, wfSInfo.workspace) &&
        Objects.equals(this.enabled, wfSInfo.enabled) &&
        Objects.equals(this.name, wfSInfo.name) &&
        Objects.equals(this.title, wfSInfo.title) &&
        Objects.equals(this.abstrct, wfSInfo.abstrct) &&
        Objects.equals(this.maintainer, wfSInfo.maintainer) &&
        Objects.equals(this.accessConstraints, wfSInfo.accessConstraints) &&
        Objects.equals(this.fees, wfSInfo.fees) &&
        Objects.equals(this.exceptionFormats, wfSInfo.exceptionFormats) &&
        Objects.equals(this.citeCompliant, wfSInfo.citeCompliant) &&
        Objects.equals(this.onlineResource, wfSInfo.onlineResource) &&
        Objects.equals(this.schemaBaseURL, wfSInfo.schemaBaseURL) &&
        Objects.equals(this.outputStrategy, wfSInfo.outputStrategy) &&
        Objects.equals(this.verbose, wfSInfo.verbose) &&
        Objects.equals(this.gml, wfSInfo.gml) &&
        Objects.equals(this.serviceLevel, wfSInfo.serviceLevel) &&
        Objects.equals(this.maxFeatures, wfSInfo.maxFeatures) &&
        Objects.equals(this.featureBounding, wfSInfo.featureBounding) &&
        Objects.equals(this.canonicalSchemaLocation, wfSInfo.canonicalSchemaLocation) &&
        Objects.equals(this.encodeFeatureMember, wfSInfo.encodeFeatureMember) &&
        Objects.equals(this.hitsIgnoreMaxFeatures, wfSInfo.hitsIgnoreMaxFeatures) &&
        Objects.equals(this.getFeatureOutputTypeCheckingEnabled, wfSInfo.getFeatureOutputTypeCheckingEnabled) &&
        Objects.equals(this.getFeatureOutputTypes, wfSInfo.getFeatureOutputTypes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(workspace, enabled, name, title, abstrct, maintainer, accessConstraints, fees, exceptionFormats, citeCompliant, onlineResource, schemaBaseURL, outputStrategy, verbose, gml, serviceLevel, maxFeatures, featureBounding, canonicalSchemaLocation, encodeFeatureMember, hitsIgnoreMaxFeatures, getFeatureOutputTypeCheckingEnabled, getFeatureOutputTypes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WFSInfo {\n");
    sb.append("    workspace: ").append(toIndentedString(workspace)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    abstrct: ").append(toIndentedString(abstrct)).append("\n");
    sb.append("    maintainer: ").append(toIndentedString(maintainer)).append("\n");
    sb.append("    accessConstraints: ").append(toIndentedString(accessConstraints)).append("\n");
    sb.append("    fees: ").append(toIndentedString(fees)).append("\n");
    sb.append("    exceptionFormats: ").append(toIndentedString(exceptionFormats)).append("\n");
    sb.append("    citeCompliant: ").append(toIndentedString(citeCompliant)).append("\n");
    sb.append("    onlineResource: ").append(toIndentedString(onlineResource)).append("\n");
    sb.append("    schemaBaseURL: ").append(toIndentedString(schemaBaseURL)).append("\n");
    sb.append("    outputStrategy: ").append(toIndentedString(outputStrategy)).append("\n");
    sb.append("    verbose: ").append(toIndentedString(verbose)).append("\n");
    sb.append("    gml: ").append(toIndentedString(gml)).append("\n");
    sb.append("    serviceLevel: ").append(toIndentedString(serviceLevel)).append("\n");
    sb.append("    maxFeatures: ").append(toIndentedString(maxFeatures)).append("\n");
    sb.append("    featureBounding: ").append(toIndentedString(featureBounding)).append("\n");
    sb.append("    canonicalSchemaLocation: ").append(toIndentedString(canonicalSchemaLocation)).append("\n");
    sb.append("    encodeFeatureMember: ").append(toIndentedString(encodeFeatureMember)).append("\n");
    sb.append("    hitsIgnoreMaxFeatures: ").append(toIndentedString(hitsIgnoreMaxFeatures)).append("\n");
    sb.append("    getFeatureOutputTypeCheckingEnabled: ").append(toIndentedString(getFeatureOutputTypeCheckingEnabled)).append("\n");
    sb.append("    getFeatureOutputTypes: ").append(toIndentedString(getFeatureOutputTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

