/*
 * GeoServer Config Model
 * GeoServer Config Model Objects
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.geoserver.openapi.model.config;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.geoserver.openapi.model.config.GetMapMimeTypes;
import org.geoserver.openapi.model.config.SRSListWrapper;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * WMSInfoAllOf
 */
@JsonPropertyOrder({
  WMSInfoAllOf.JSON_PROPERTY_SRS,
  WMSInfoAllOf.JSON_PROPERTY_INTERPOLATION,
  WMSInfoAllOf.JSON_PROPERTY_GET_FEATURE_INFO_MIME_TYPE_CHECKING_ENABLED,
  WMSInfoAllOf.JSON_PROPERTY_GET_MAP_MIME_TYPES,
  WMSInfoAllOf.JSON_PROPERTY_GET_MAP_MIME_TYPE_CHECKING_ENABLED,
  WMSInfoAllOf.JSON_PROPERTY_DYNAMIC_STYLING_DISABLED,
  WMSInfoAllOf.JSON_PROPERTY_MAX_BUFFER,
  WMSInfoAllOf.JSON_PROPERTY_MAX_REQUEST_MEMORY,
  WMSInfoAllOf.JSON_PROPERTY_MAX_RENDERING_TIME,
  WMSInfoAllOf.JSON_PROPERTY_MAX_RENDERING_ERRORS
})

public class WMSInfoAllOf {
  public static final String JSON_PROPERTY_SRS = "srs";
  private SRSListWrapper srs;

  /**
   * Gets or Sets interpolation
   */
  public enum InterpolationEnum {
    NEAREST("Nearest"),
    
    BILINEAR("Bilinear"),
    
    BICUBIC("Bicubic");

    private String value;

    InterpolationEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static InterpolationEnum fromValue(String value) {
      for (InterpolationEnum b : InterpolationEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_INTERPOLATION = "interpolation";
  private InterpolationEnum interpolation;

  public static final String JSON_PROPERTY_GET_FEATURE_INFO_MIME_TYPE_CHECKING_ENABLED = "getFeatureInfoMimeTypeCheckingEnabled";
  private Boolean getFeatureInfoMimeTypeCheckingEnabled;

  public static final String JSON_PROPERTY_GET_MAP_MIME_TYPES = "getMapMimeTypes";
  private GetMapMimeTypes getMapMimeTypes;

  public static final String JSON_PROPERTY_GET_MAP_MIME_TYPE_CHECKING_ENABLED = "getMapMimeTypeCheckingEnabled";
  private Boolean getMapMimeTypeCheckingEnabled;

  public static final String JSON_PROPERTY_DYNAMIC_STYLING_DISABLED = "dynamicStylingDisabled";
  private Boolean dynamicStylingDisabled;

  public static final String JSON_PROPERTY_MAX_BUFFER = "maxBuffer";
  private Integer maxBuffer;

  public static final String JSON_PROPERTY_MAX_REQUEST_MEMORY = "maxRequestMemory";
  private Integer maxRequestMemory;

  public static final String JSON_PROPERTY_MAX_RENDERING_TIME = "maxRenderingTime";
  private Integer maxRenderingTime;

  public static final String JSON_PROPERTY_MAX_RENDERING_ERRORS = "maxRenderingErrors";
  private Integer maxRenderingErrors;


  public WMSInfoAllOf srs(SRSListWrapper srs) {
    
    this.srs = srs;
    return this;
  }

   /**
   * Get srs
   * @return srs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SRS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SRSListWrapper getSrs() {
    return srs;
  }


  public void setSrs(SRSListWrapper srs) {
    this.srs = srs;
  }


  public WMSInfoAllOf interpolation(InterpolationEnum interpolation) {
    
    this.interpolation = interpolation;
    return this;
  }

   /**
   * Get interpolation
   * @return interpolation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_INTERPOLATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public InterpolationEnum getInterpolation() {
    return interpolation;
  }


  public void setInterpolation(InterpolationEnum interpolation) {
    this.interpolation = interpolation;
  }


  public WMSInfoAllOf getFeatureInfoMimeTypeCheckingEnabled(Boolean getFeatureInfoMimeTypeCheckingEnabled) {
    
    this.getFeatureInfoMimeTypeCheckingEnabled = getFeatureInfoMimeTypeCheckingEnabled;
    return this;
  }

   /**
   * Flag indicating if getFeatureInfo MIME type checking is enabled
   * @return getFeatureInfoMimeTypeCheckingEnabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Flag indicating if getFeatureInfo MIME type checking is enabled")
  @JsonProperty(JSON_PROPERTY_GET_FEATURE_INFO_MIME_TYPE_CHECKING_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getGetFeatureInfoMimeTypeCheckingEnabled() {
    return getFeatureInfoMimeTypeCheckingEnabled;
  }


  public void setGetFeatureInfoMimeTypeCheckingEnabled(Boolean getFeatureInfoMimeTypeCheckingEnabled) {
    this.getFeatureInfoMimeTypeCheckingEnabled = getFeatureInfoMimeTypeCheckingEnabled;
  }


  public WMSInfoAllOf getMapMimeTypes(GetMapMimeTypes getMapMimeTypes) {
    
    this.getMapMimeTypes = getMapMimeTypes;
    return this;
  }

   /**
   * Get getMapMimeTypes
   * @return getMapMimeTypes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GET_MAP_MIME_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GetMapMimeTypes getGetMapMimeTypes() {
    return getMapMimeTypes;
  }


  public void setGetMapMimeTypes(GetMapMimeTypes getMapMimeTypes) {
    this.getMapMimeTypes = getMapMimeTypes;
  }


  public WMSInfoAllOf getMapMimeTypeCheckingEnabled(Boolean getMapMimeTypeCheckingEnabled) {
    
    this.getMapMimeTypeCheckingEnabled = getMapMimeTypeCheckingEnabled;
    return this;
  }

   /**
   * Flag indicating if getMap MIME type checking is enabled.
   * @return getMapMimeTypeCheckingEnabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Flag indicating if getMap MIME type checking is enabled.")
  @JsonProperty(JSON_PROPERTY_GET_MAP_MIME_TYPE_CHECKING_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getGetMapMimeTypeCheckingEnabled() {
    return getMapMimeTypeCheckingEnabled;
  }


  public void setGetMapMimeTypeCheckingEnabled(Boolean getMapMimeTypeCheckingEnabled) {
    this.getMapMimeTypeCheckingEnabled = getMapMimeTypeCheckingEnabled;
  }


  public WMSInfoAllOf dynamicStylingDisabled(Boolean dynamicStylingDisabled) {
    
    this.dynamicStylingDisabled = dynamicStylingDisabled;
    return this;
  }

   /**
   * status of dynamic styling (SLD and SLD_BODY params) allowance
   * @return dynamicStylingDisabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "status of dynamic styling (SLD and SLD_BODY params) allowance")
  @JsonProperty(JSON_PROPERTY_DYNAMIC_STYLING_DISABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDynamicStylingDisabled() {
    return dynamicStylingDisabled;
  }


  public void setDynamicStylingDisabled(Boolean dynamicStylingDisabled) {
    this.dynamicStylingDisabled = dynamicStylingDisabled;
  }


  public WMSInfoAllOf maxBuffer(Integer maxBuffer) {
    
    this.maxBuffer = maxBuffer;
    return this;
  }

   /**
   * Maximum search radius for GetFeatureInfo
   * @return maxBuffer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Maximum search radius for GetFeatureInfo")
  @JsonProperty(JSON_PROPERTY_MAX_BUFFER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaxBuffer() {
    return maxBuffer;
  }


  public void setMaxBuffer(Integer maxBuffer) {
    this.maxBuffer = maxBuffer;
  }


  public WMSInfoAllOf maxRequestMemory(Integer maxRequestMemory) {
    
    this.maxRequestMemory = maxRequestMemory;
    return this;
  }

   /**
   * Max amount of memory, in kilobytes, that each WMS request can allocate (each output format will make a best effort attempt to respect it, but there are no guarantees). 0 indicates no limit.
   * @return maxRequestMemory
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Max amount of memory, in kilobytes, that each WMS request can allocate (each output format will make a best effort attempt to respect it, but there are no guarantees). 0 indicates no limit.")
  @JsonProperty(JSON_PROPERTY_MAX_REQUEST_MEMORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaxRequestMemory() {
    return maxRequestMemory;
  }


  public void setMaxRequestMemory(Integer maxRequestMemory) {
    this.maxRequestMemory = maxRequestMemory;
  }


  public WMSInfoAllOf maxRenderingTime(Integer maxRenderingTime) {
    
    this.maxRenderingTime = maxRenderingTime;
    return this;
  }

   /**
   * Max time, in seconds, a WMS request is allowed to spend rendering the map. Various output formats will do a best effort to respect it (raster formats, for example, will account just rendering time, but not image encoding time).
   * @return maxRenderingTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Max time, in seconds, a WMS request is allowed to spend rendering the map. Various output formats will do a best effort to respect it (raster formats, for example, will account just rendering time, but not image encoding time).")
  @JsonProperty(JSON_PROPERTY_MAX_RENDERING_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaxRenderingTime() {
    return maxRenderingTime;
  }


  public void setMaxRenderingTime(Integer maxRenderingTime) {
    this.maxRenderingTime = maxRenderingTime;
  }


  public WMSInfoAllOf maxRenderingErrors(Integer maxRenderingErrors) {
    
    this.maxRenderingErrors = maxRenderingErrors;
    return this;
  }

   /**
   * Max number of rendering errors that will be tolerated before stating the rendering operation failed by throwing a service exception back to the client
   * @return maxRenderingErrors
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Max number of rendering errors that will be tolerated before stating the rendering operation failed by throwing a service exception back to the client")
  @JsonProperty(JSON_PROPERTY_MAX_RENDERING_ERRORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaxRenderingErrors() {
    return maxRenderingErrors;
  }


  public void setMaxRenderingErrors(Integer maxRenderingErrors) {
    this.maxRenderingErrors = maxRenderingErrors;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WMSInfoAllOf wmSInfoAllOf = (WMSInfoAllOf) o;
    return Objects.equals(this.srs, wmSInfoAllOf.srs) &&
        Objects.equals(this.interpolation, wmSInfoAllOf.interpolation) &&
        Objects.equals(this.getFeatureInfoMimeTypeCheckingEnabled, wmSInfoAllOf.getFeatureInfoMimeTypeCheckingEnabled) &&
        Objects.equals(this.getMapMimeTypes, wmSInfoAllOf.getMapMimeTypes) &&
        Objects.equals(this.getMapMimeTypeCheckingEnabled, wmSInfoAllOf.getMapMimeTypeCheckingEnabled) &&
        Objects.equals(this.dynamicStylingDisabled, wmSInfoAllOf.dynamicStylingDisabled) &&
        Objects.equals(this.maxBuffer, wmSInfoAllOf.maxBuffer) &&
        Objects.equals(this.maxRequestMemory, wmSInfoAllOf.maxRequestMemory) &&
        Objects.equals(this.maxRenderingTime, wmSInfoAllOf.maxRenderingTime) &&
        Objects.equals(this.maxRenderingErrors, wmSInfoAllOf.maxRenderingErrors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(srs, interpolation, getFeatureInfoMimeTypeCheckingEnabled, getMapMimeTypes, getMapMimeTypeCheckingEnabled, dynamicStylingDisabled, maxBuffer, maxRequestMemory, maxRenderingTime, maxRenderingErrors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WMSInfoAllOf {\n");
    sb.append("    srs: ").append(toIndentedString(srs)).append("\n");
    sb.append("    interpolation: ").append(toIndentedString(interpolation)).append("\n");
    sb.append("    getFeatureInfoMimeTypeCheckingEnabled: ").append(toIndentedString(getFeatureInfoMimeTypeCheckingEnabled)).append("\n");
    sb.append("    getMapMimeTypes: ").append(toIndentedString(getMapMimeTypes)).append("\n");
    sb.append("    getMapMimeTypeCheckingEnabled: ").append(toIndentedString(getMapMimeTypeCheckingEnabled)).append("\n");
    sb.append("    dynamicStylingDisabled: ").append(toIndentedString(dynamicStylingDisabled)).append("\n");
    sb.append("    maxBuffer: ").append(toIndentedString(maxBuffer)).append("\n");
    sb.append("    maxRequestMemory: ").append(toIndentedString(maxRequestMemory)).append("\n");
    sb.append("    maxRenderingTime: ").append(toIndentedString(maxRenderingTime)).append("\n");
    sb.append("    maxRenderingErrors: ").append(toIndentedString(maxRenderingErrors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

