/*
 * GeoServer Data Stores
 * A data store contains vector format spatial data. It can be a file (such as a shapefile), a database (such as PostGIS), or a server (such as a remote Web Feature Service).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.geoserver.openapi.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ConnectionParameterEntry
 */
@JsonPropertyOrder({
  ConnectionParameterEntry.JSON_PROPERTY_AT_KEY,
  ConnectionParameterEntry.JSON_PROPERTY_VALUE
})

public class ConnectionParameterEntry {
  public static final String JSON_PROPERTY_AT_KEY = "@key";
  private String atKey;

  public static final String JSON_PROPERTY_VALUE = "$";
  private String value;


  public ConnectionParameterEntry atKey(String atKey) {
    
    this.atKey = atKey;
    return this;
  }

   /**
   * Connection parameter key
   * @return atKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Connection parameter key")
  @JsonProperty(JSON_PROPERTY_AT_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAtKey() {
    return atKey;
  }


  public void setAtKey(String atKey) {
    this.atKey = atKey;
  }


  public ConnectionParameterEntry value(String value) {
    
    this.value = value;
    return this;
  }

   /**
   * Connection parameter value
   * @return value
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Connection parameter value")
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValue() {
    return value;
  }


  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConnectionParameterEntry connectionParameterEntry = (ConnectionParameterEntry) o;
    return Objects.equals(this.atKey, connectionParameterEntry.atKey) &&
        Objects.equals(this.value, connectionParameterEntry.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(atKey, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConnectionParameterEntry {\n");
    sb.append("    atKey: ").append(toIndentedString(atKey)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

