/*
 * GeoServer Global Config
 * Global configuration settings
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.geoserver.openapi.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ContactInfoWrapper
 */
@JsonPropertyOrder({
  ContactInfoWrapper.JSON_PROPERTY_CONTACT
})

public class ContactInfoWrapper {
  public static final String JSON_PROPERTY_CONTACT = "contact";
  private org.geoserver.openapi.model.config.ContactInfo contact;


  public ContactInfoWrapper contact(org.geoserver.openapi.model.config.ContactInfo contact) {
    
    this.contact = contact;
    return this;
  }

   /**
   * Get contact
   * @return contact
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CONTACT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public org.geoserver.openapi.model.config.ContactInfo getContact() {
    return contact;
  }


  public void setContact(org.geoserver.openapi.model.config.ContactInfo contact) {
    this.contact = contact;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContactInfoWrapper contactInfoWrapper = (ContactInfoWrapper) o;
    return Objects.equals(this.contact, contactInfoWrapper.contact);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contact);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContactInfoWrapper {\n");
    sb.append("    contact: ").append(toIndentedString(contact)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

