/*
 * GeoServer CoverageStores
 * A coverage store describes how access a raster data source.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.geoserver.openapi.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.geoserver.openapi.v1.model.CoverageStoreListWrapper;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * CoverageStoresResponse
 */
@JsonPropertyOrder({
  CoverageStoresResponse.JSON_PROPERTY_COVERAGE_STORES
})

public class CoverageStoresResponse {
  public static final String JSON_PROPERTY_COVERAGE_STORES = "coverageStores";
  private CoverageStoreListWrapper coverageStores;


  public CoverageStoresResponse coverageStores(CoverageStoreListWrapper coverageStores) {
    
    this.coverageStores = coverageStores;
    return this;
  }

   /**
   * Get coverageStores
   * @return coverageStores
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_COVERAGE_STORES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public CoverageStoreListWrapper getCoverageStores() {
    return coverageStores;
  }


  public void setCoverageStores(CoverageStoreListWrapper coverageStores) {
    this.coverageStores = coverageStores;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CoverageStoresResponse coverageStoresResponse = (CoverageStoresResponse) o;
    return Objects.equals(this.coverageStores, coverageStoresResponse.coverageStores);
  }

  @Override
  public int hashCode() {
    return Objects.hash(coverageStores);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CoverageStoresResponse {\n");
    sb.append("    coverageStores: ").append(toIndentedString(coverageStores)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

