/*
 * GeoServer Coverages
 * A coverage is a raster data set which originates from a coverage store.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.geoserver.openapi.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.geoserver.openapi.v1.model.CoverageDimensionResponse;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * CoverageDimensionsWrapper
 */
@JsonPropertyOrder({
  CoverageDimensionsWrapper.JSON_PROPERTY_COVERAGE_DIMENSION
})

public class CoverageDimensionsWrapper {
  public static final String JSON_PROPERTY_COVERAGE_DIMENSION = "coverageDimension";
  private List<CoverageDimensionResponse> coverageDimension = null;


  public CoverageDimensionsWrapper coverageDimension(List<CoverageDimensionResponse> coverageDimension) {
    
    this.coverageDimension = coverageDimension;
    return this;
  }

  public CoverageDimensionsWrapper addCoverageDimensionItem(CoverageDimensionResponse coverageDimensionItem) {
    if (this.coverageDimension == null) {
      this.coverageDimension = new ArrayList<>();
    }
    this.coverageDimension.add(coverageDimensionItem);
    return this;
  }

   /**
   * Get coverageDimension
   * @return coverageDimension
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_COVERAGE_DIMENSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CoverageDimensionResponse> getCoverageDimension() {
    return coverageDimension;
  }


  public void setCoverageDimension(List<CoverageDimensionResponse> coverageDimension) {
    this.coverageDimension = coverageDimension;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CoverageDimensionsWrapper coverageDimensionsWrapper = (CoverageDimensionsWrapper) o;
    return Objects.equals(this.coverageDimension, coverageDimensionsWrapper.coverageDimension);
  }

  @Override
  public int hashCode() {
    return Objects.hash(coverageDimension);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CoverageDimensionsWrapper {\n");
    sb.append("    coverageDimension: ").append(toIndentedString(coverageDimension)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

