/*
 * GeoServer Coverages
 * A coverage is a raster data set which originates from a coverage store.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.geoserver.openapi.v1.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * CoverageDimensionResponse
 */
@JsonPropertyOrder({
  CoverageDimensionResponse.JSON_PROPERTY_ID,
  CoverageDimensionResponse.JSON_PROPERTY_NAME,
  CoverageDimensionResponse.JSON_PROPERTY_DESCRIPTION,
  CoverageDimensionResponse.JSON_PROPERTY_RANGE,
  CoverageDimensionResponse.JSON_PROPERTY_NULL_VALUES,
  CoverageDimensionResponse.JSON_PROPERTY_UNIT
})

public class CoverageDimensionResponse {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_RANGE = "range";
  private NumberRangeResponse range;

  public static final String JSON_PROPERTY_NULL_VALUES = "nullValues";
  private DoubleArrayResponse nullValues;

  public static final String JSON_PROPERTY_UNIT = "unit";
  private String unit;


  public CoverageDimensionResponse id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public CoverageDimensionResponse name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public CoverageDimensionResponse description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public CoverageDimensionResponse range(NumberRangeResponse range) {
    
    this.range = range;
    return this;
  }

   /**
   * Get range
   * @return range
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public NumberRangeResponse getRange() {
    return range;
  }


  public void setRange(NumberRangeResponse range) {
    this.range = range;
  }


  public CoverageDimensionResponse nullValues(DoubleArrayResponse nullValues) {
    
    this.nullValues = nullValues;
    return this;
  }

   /**
   * Get nullValues
   * @return nullValues
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NULL_VALUES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DoubleArrayResponse getNullValues() {
    return nullValues;
  }


  public void setNullValues(DoubleArrayResponse nullValues) {
    this.nullValues = nullValues;
  }


  public CoverageDimensionResponse unit(String unit) {
    
    this.unit = unit;
    return this;
  }

   /**
   * Get unit
   * @return unit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UNIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUnit() {
    return unit;
  }


  public void setUnit(String unit) {
    this.unit = unit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CoverageDimensionResponse coverageDimensionResponse = (CoverageDimensionResponse) o;
    return Objects.equals(this.id, coverageDimensionResponse.id) &&
        Objects.equals(this.name, coverageDimensionResponse.name) &&
        Objects.equals(this.description, coverageDimensionResponse.description) &&
        Objects.equals(this.range, coverageDimensionResponse.range) &&
        Objects.equals(this.nullValues, coverageDimensionResponse.nullValues) &&
        Objects.equals(this.unit, coverageDimensionResponse.unit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, range, nullValues, unit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CoverageDimensionResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    range: ").append(toIndentedString(range)).append("\n");
    sb.append("    nullValues: ").append(toIndentedString(nullValues)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

