/*
 * GeoServer Coverages
 * A coverage is a raster data set which originates from a coverage store.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.geoserver.openapi.v1.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * CoverageResponseAllOf
 */
@JsonPropertyOrder({
  CoverageResponseAllOf.JSON_PROPERTY_NATIVE_COVERAGE_NAME,
  CoverageResponseAllOf.JSON_PROPERTY_NATIVE_FORMAT,
  CoverageResponseAllOf.JSON_PROPERTY_SUPPORTED_FORMATS,
  CoverageResponseAllOf.JSON_PROPERTY_REQUEST_S_R_S,
  CoverageResponseAllOf.JSON_PROPERTY_RESPONSE_S_R_S,
  CoverageResponseAllOf.JSON_PROPERTY_DEFAULT_INTERPOLATION_METHOD,
  CoverageResponseAllOf.JSON_PROPERTY_INTERPOLATION_METHODS,
  CoverageResponseAllOf.JSON_PROPERTY_PARAMETERS,
  CoverageResponseAllOf.JSON_PROPERTY_DIMENSIONS,
  CoverageResponseAllOf.JSON_PROPERTY_GRID
})

public class CoverageResponseAllOf {
  public static final String JSON_PROPERTY_NATIVE_COVERAGE_NAME = "nativeCoverageName";
  private String nativeCoverageName;

  public static final String JSON_PROPERTY_NATIVE_FORMAT = "nativeFormat";
  private String nativeFormat;

  public static final String JSON_PROPERTY_SUPPORTED_FORMATS = "supportedFormats";
  private StringArrayResponse supportedFormats;

  public static final String JSON_PROPERTY_REQUEST_S_R_S = "requestSRS";
  private StringArrayResponse requestSRS;

  public static final String JSON_PROPERTY_RESPONSE_S_R_S = "responseSRS";
  private StringArrayResponse responseSRS;

  public static final String JSON_PROPERTY_DEFAULT_INTERPOLATION_METHOD = "defaultInterpolationMethod";
  private String defaultInterpolationMethod;

  public static final String JSON_PROPERTY_INTERPOLATION_METHODS = "interpolationMethods";
  private StringArrayResponse interpolationMethods;

  public static final String JSON_PROPERTY_PARAMETERS = "parameters";
  private Map<String, Object> parameters = null;

  public static final String JSON_PROPERTY_DIMENSIONS = "dimensions";
  private CoverageDimensionsWrapper dimensions;

  public static final String JSON_PROPERTY_GRID = "grid";
  private GridInfoResponse grid;


  public CoverageResponseAllOf nativeCoverageName(String nativeCoverageName) {
    
    this.nativeCoverageName = nativeCoverageName;
    return this;
  }

   /**
   * the native coverage name (used to pick up a specific coverage from within a reader)
   * @return nativeCoverageName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "the native coverage name (used to pick up a specific coverage from within a reader)")
  @JsonProperty(JSON_PROPERTY_NATIVE_COVERAGE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNativeCoverageName() {
    return nativeCoverageName;
  }


  public void setNativeCoverageName(String nativeCoverageName) {
    this.nativeCoverageName = nativeCoverageName;
  }


  public CoverageResponseAllOf nativeFormat(String nativeFormat) {
    
    this.nativeFormat = nativeFormat;
    return this;
  }

   /**
   * Get nativeFormat
   * @return nativeFormat
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NATIVE_FORMAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNativeFormat() {
    return nativeFormat;
  }


  public void setNativeFormat(String nativeFormat) {
    this.nativeFormat = nativeFormat;
  }


  public CoverageResponseAllOf supportedFormats(StringArrayResponse supportedFormats) {
    
    this.supportedFormats = supportedFormats;
    return this;
  }

   /**
   * Get supportedFormats
   * @return supportedFormats
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SUPPORTED_FORMATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StringArrayResponse getSupportedFormats() {
    return supportedFormats;
  }


  public void setSupportedFormats(StringArrayResponse supportedFormats) {
    this.supportedFormats = supportedFormats;
  }


  public CoverageResponseAllOf requestSRS(StringArrayResponse requestSRS) {
    
    this.requestSRS = requestSRS;
    return this;
  }

   /**
   * Get requestSRS
   * @return requestSRS
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REQUEST_S_R_S)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StringArrayResponse getRequestSRS() {
    return requestSRS;
  }


  public void setRequestSRS(StringArrayResponse requestSRS) {
    this.requestSRS = requestSRS;
  }


  public CoverageResponseAllOf responseSRS(StringArrayResponse responseSRS) {
    
    this.responseSRS = responseSRS;
    return this;
  }

   /**
   * Get responseSRS
   * @return responseSRS
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RESPONSE_S_R_S)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StringArrayResponse getResponseSRS() {
    return responseSRS;
  }


  public void setResponseSRS(StringArrayResponse responseSRS) {
    this.responseSRS = responseSRS;
  }


  public CoverageResponseAllOf defaultInterpolationMethod(String defaultInterpolationMethod) {
    
    this.defaultInterpolationMethod = defaultInterpolationMethod;
    return this;
  }

   /**
   * Get defaultInterpolationMethod
   * @return defaultInterpolationMethod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DEFAULT_INTERPOLATION_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDefaultInterpolationMethod() {
    return defaultInterpolationMethod;
  }


  public void setDefaultInterpolationMethod(String defaultInterpolationMethod) {
    this.defaultInterpolationMethod = defaultInterpolationMethod;
  }


  public CoverageResponseAllOf interpolationMethods(StringArrayResponse interpolationMethods) {
    
    this.interpolationMethods = interpolationMethods;
    return this;
  }

   /**
   * Get interpolationMethods
   * @return interpolationMethods
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_INTERPOLATION_METHODS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StringArrayResponse getInterpolationMethods() {
    return interpolationMethods;
  }


  public void setInterpolationMethods(StringArrayResponse interpolationMethods) {
    this.interpolationMethods = interpolationMethods;
  }


  public CoverageResponseAllOf parameters(Map<String, Object> parameters) {
    
    this.parameters = parameters;
    return this;
  }

  public CoverageResponseAllOf putParametersItem(String key, Object parametersItem) {
    if (this.parameters == null) {
      this.parameters = new HashMap<>();
    }
    this.parameters.put(key, parametersItem);
    return this;
  }

   /**
   * Get parameters
   * @return parameters
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getParameters() {
    return parameters;
  }


  public void setParameters(Map<String, Object> parameters) {
    this.parameters = parameters;
  }


  public CoverageResponseAllOf dimensions(CoverageDimensionsWrapper dimensions) {
    
    this.dimensions = dimensions;
    return this;
  }

   /**
   * Get dimensions
   * @return dimensions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DIMENSIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CoverageDimensionsWrapper getDimensions() {
    return dimensions;
  }


  public void setDimensions(CoverageDimensionsWrapper dimensions) {
    this.dimensions = dimensions;
  }


  public CoverageResponseAllOf grid(GridInfoResponse grid) {
    
    this.grid = grid;
    return this;
  }

   /**
   * Get grid
   * @return grid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GRID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GridInfoResponse getGrid() {
    return grid;
  }


  public void setGrid(GridInfoResponse grid) {
    this.grid = grid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CoverageResponseAllOf coverageResponseAllOf = (CoverageResponseAllOf) o;
    return Objects.equals(this.nativeCoverageName, coverageResponseAllOf.nativeCoverageName) &&
        Objects.equals(this.nativeFormat, coverageResponseAllOf.nativeFormat) &&
        Objects.equals(this.supportedFormats, coverageResponseAllOf.supportedFormats) &&
        Objects.equals(this.requestSRS, coverageResponseAllOf.requestSRS) &&
        Objects.equals(this.responseSRS, coverageResponseAllOf.responseSRS) &&
        Objects.equals(this.defaultInterpolationMethod, coverageResponseAllOf.defaultInterpolationMethod) &&
        Objects.equals(this.interpolationMethods, coverageResponseAllOf.interpolationMethods) &&
        Objects.equals(this.parameters, coverageResponseAllOf.parameters) &&
        Objects.equals(this.dimensions, coverageResponseAllOf.dimensions) &&
        Objects.equals(this.grid, coverageResponseAllOf.grid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nativeCoverageName, nativeFormat, supportedFormats, requestSRS, responseSRS, defaultInterpolationMethod, interpolationMethods, parameters, dimensions, grid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CoverageResponseAllOf {\n");
    sb.append("    nativeCoverageName: ").append(toIndentedString(nativeCoverageName)).append("\n");
    sb.append("    nativeFormat: ").append(toIndentedString(nativeFormat)).append("\n");
    sb.append("    supportedFormats: ").append(toIndentedString(supportedFormats)).append("\n");
    sb.append("    requestSRS: ").append(toIndentedString(requestSRS)).append("\n");
    sb.append("    responseSRS: ").append(toIndentedString(responseSRS)).append("\n");
    sb.append("    defaultInterpolationMethod: ").append(toIndentedString(defaultInterpolationMethod)).append("\n");
    sb.append("    interpolationMethods: ").append(toIndentedString(interpolationMethods)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("    dimensions: ").append(toIndentedString(dimensions)).append("\n");
    sb.append("    grid: ").append(toIndentedString(grid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

