/*
 * GeoServer Coverages
 * A coverage is a raster data set which originates from a coverage store.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.geoserver.openapi.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * DoubleArrayResponse
 */
@JsonPropertyOrder({
  DoubleArrayResponse.JSON_PROPERTY_DOUBLE
})

public class DoubleArrayResponse {
  public static final String JSON_PROPERTY_DOUBLE = "double";
  private List<Double> _double = null;


  public DoubleArrayResponse _double(List<Double> _double) {
    
    this._double = _double;
    return this;
  }

  public DoubleArrayResponse addDoubleItem(Double _doubleItem) {
    if (this._double == null) {
      this._double = new ArrayList<>();
    }
    this._double.add(_doubleItem);
    return this;
  }

   /**
   * Get _double
   * @return _double
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DOUBLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Double> getDouble() {
    return _double;
  }


  public void setDouble(List<Double> _double) {
    this._double = _double;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DoubleArrayResponse doubleArrayResponse = (DoubleArrayResponse) o;
    return Objects.equals(this._double, doubleArrayResponse._double);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_double);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DoubleArrayResponse {\n");
    sb.append("    _double: ").append(toIndentedString(_double)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

