/*
 * GeoServer Coverages
 * A coverage is a raster data set which originates from a coverage store.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.geoserver.openapi.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * EnvelopeResponse
 */
@JsonPropertyOrder({
  EnvelopeResponse.JSON_PROPERTY_MINX,
  EnvelopeResponse.JSON_PROPERTY_MAXX,
  EnvelopeResponse.JSON_PROPERTY_MINY,
  EnvelopeResponse.JSON_PROPERTY_MAXY,
  EnvelopeResponse.JSON_PROPERTY_CRS
})

public class EnvelopeResponse {
  public static final String JSON_PROPERTY_MINX = "minx";
  private Double minx;

  public static final String JSON_PROPERTY_MAXX = "maxx";
  private Double maxx;

  public static final String JSON_PROPERTY_MINY = "miny";
  private Double miny;

  public static final String JSON_PROPERTY_MAXY = "maxy";
  private Double maxy;

  public static final String JSON_PROPERTY_CRS = "crs";
  private Object crs;


  public EnvelopeResponse minx(Double minx) {
    
    this.minx = minx;
    return this;
  }

   /**
   * Get minx
   * @return minx
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MINX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getMinx() {
    return minx;
  }


  public void setMinx(Double minx) {
    this.minx = minx;
  }


  public EnvelopeResponse maxx(Double maxx) {
    
    this.maxx = maxx;
    return this;
  }

   /**
   * Get maxx
   * @return maxx
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MAXX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getMaxx() {
    return maxx;
  }


  public void setMaxx(Double maxx) {
    this.maxx = maxx;
  }


  public EnvelopeResponse miny(Double miny) {
    
    this.miny = miny;
    return this;
  }

   /**
   * Get miny
   * @return miny
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MINY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getMiny() {
    return miny;
  }


  public void setMiny(Double miny) {
    this.miny = miny;
  }


  public EnvelopeResponse maxy(Double maxy) {
    
    this.maxy = maxy;
    return this;
  }

   /**
   * Get maxy
   * @return maxy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MAXY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getMaxy() {
    return maxy;
  }


  public void setMaxy(Double maxy) {
    this.maxy = maxy;
  }


  public EnvelopeResponse crs(Object crs) {
    
    this.crs = crs;
    return this;
  }

   /**
   * left as a free form object because geoserver returns a  plain string if it is a geographic crs (e.g. \&quot;EPSG:4326\&quot;) or an object like this: {\&quot;@class\&quot;:\&quot;projected\&quot;,\&quot;$\&quot;:\&quot;EPSG:26986\&quot;}
   * @return crs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "left as a free form object because geoserver returns a  plain string if it is a geographic crs (e.g. \"EPSG:4326\") or an object like this: {\"@class\":\"projected\",\"$\":\"EPSG:26986\"}")
  @JsonProperty(JSON_PROPERTY_CRS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getCrs() {
    return crs;
  }


  public void setCrs(Object crs) {
    this.crs = crs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnvelopeResponse envelopeResponse = (EnvelopeResponse) o;
    return Objects.equals(this.minx, envelopeResponse.minx) &&
        Objects.equals(this.maxx, envelopeResponse.maxx) &&
        Objects.equals(this.miny, envelopeResponse.miny) &&
        Objects.equals(this.maxy, envelopeResponse.maxy) &&
        Objects.equals(this.crs, envelopeResponse.crs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(minx, maxx, miny, maxy, crs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnvelopeResponse {\n");
    sb.append("    minx: ").append(toIndentedString(minx)).append("\n");
    sb.append("    maxx: ").append(toIndentedString(maxx)).append("\n");
    sb.append("    miny: ").append(toIndentedString(miny)).append("\n");
    sb.append("    maxy: ").append(toIndentedString(maxy)).append("\n");
    sb.append("    crs: ").append(toIndentedString(crs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

