/*
 * GeoServer Layers
 * A layer is a published resource (feature type or coverage).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.geoserver.openapi.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.geoserver.openapi.v1.model.MetadataLinks;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * LayerGroupInfoAllOf
 */
@JsonPropertyOrder({
  LayerGroupInfoAllOf.JSON_PROPERTY_MODE,
  LayerGroupInfoAllOf.JSON_PROPERTY_GUERY_DISABLED,
  LayerGroupInfoAllOf.JSON_PROPERTY_KEYWORDS,
  LayerGroupInfoAllOf.JSON_PROPERTY_WORKSPACE,
  LayerGroupInfoAllOf.JSON_PROPERTY_ROOT_LAYER,
  LayerGroupInfoAllOf.JSON_PROPERTY_ROOT_LAYER_STYLE,
  LayerGroupInfoAllOf.JSON_PROPERTY_LAYERS,
  LayerGroupInfoAllOf.JSON_PROPERTY_STYLES,
  LayerGroupInfoAllOf.JSON_PROPERTY_BOUNDS,
  LayerGroupInfoAllOf.JSON_PROPERTY_METADATA_LINKS
})

public class LayerGroupInfoAllOf {
  /**
   * Gets or Sets mode
   */
  public enum ModeEnum {
    SINGLE("SINGLE"),
    
    OPAQUE_CONTAINER("OPAQUE_CONTAINER"),
    
    NAMED("NAMED"),
    
    CONTAINER("CONTAINER"),
    
    EO("EO");

    private String value;

    ModeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ModeEnum fromValue(String value) {
      for (ModeEnum b : ModeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_MODE = "mode";
  private ModeEnum mode;

  public static final String JSON_PROPERTY_GUERY_DISABLED = "gueryDisabled";
  private Boolean gueryDisabled;

  public static final String JSON_PROPERTY_KEYWORDS = "keywords";
  private org.geoserver.openapi.model.catalog.KeywordInfo keywords;

  public static final String JSON_PROPERTY_WORKSPACE = "workspace";
  private org.geoserver.openapi.model.catalog.WorkspaceInfo workspace;

  public static final String JSON_PROPERTY_ROOT_LAYER = "rootLayer";
  private org.geoserver.openapi.model.catalog.LayerInfo rootLayer = null;

  public static final String JSON_PROPERTY_ROOT_LAYER_STYLE = "rootLayerStyle";
  private org.geoserver.openapi.model.catalog.StyleInfo rootLayerStyle;

  public static final String JSON_PROPERTY_LAYERS = "layers";
  private List<org.geoserver.openapi.model.catalog.PublishedInfo> layers = null;

  public static final String JSON_PROPERTY_STYLES = "styles";
  private List<org.geoserver.openapi.model.catalog.StyleInfo> styles = null;

  public static final String JSON_PROPERTY_BOUNDS = "bounds";
  private org.geoserver.openapi.model.catalog.EnvelopeInfo bounds;

  public static final String JSON_PROPERTY_METADATA_LINKS = "metadataLinks";
  private MetadataLinks metadataLinks;


  public LayerGroupInfoAllOf mode(ModeEnum mode) {
    
    this.mode = mode;
    return this;
  }

   /**
   * Get mode
   * @return mode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ModeEnum getMode() {
    return mode;
  }


  public void setMode(ModeEnum mode) {
    this.mode = mode;
  }


  public LayerGroupInfoAllOf gueryDisabled(Boolean gueryDisabled) {
    
    this.gueryDisabled = gueryDisabled;
    return this;
  }

   /**
   * Get gueryDisabled
   * @return gueryDisabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GUERY_DISABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getGueryDisabled() {
    return gueryDisabled;
  }


  public void setGueryDisabled(Boolean gueryDisabled) {
    this.gueryDisabled = gueryDisabled;
  }


  public LayerGroupInfoAllOf keywords(org.geoserver.openapi.model.catalog.KeywordInfo keywords) {
    
    this.keywords = keywords;
    return this;
  }

   /**
   * Get keywords
   * @return keywords
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_KEYWORDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public org.geoserver.openapi.model.catalog.KeywordInfo getKeywords() {
    return keywords;
  }


  public void setKeywords(org.geoserver.openapi.model.catalog.KeywordInfo keywords) {
    this.keywords = keywords;
  }


  public LayerGroupInfoAllOf workspace(org.geoserver.openapi.model.catalog.WorkspaceInfo workspace) {
    
    this.workspace = workspace;
    return this;
  }

   /**
   * Get workspace
   * @return workspace
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WORKSPACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public org.geoserver.openapi.model.catalog.WorkspaceInfo getWorkspace() {
    return workspace;
  }


  public void setWorkspace(org.geoserver.openapi.model.catalog.WorkspaceInfo workspace) {
    this.workspace = workspace;
  }


  public LayerGroupInfoAllOf rootLayer(org.geoserver.openapi.model.catalog.LayerInfo rootLayer) {
    
    this.rootLayer = rootLayer;
    return this;
  }

   /**
   * Get rootLayer
   * @return rootLayer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ROOT_LAYER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public org.geoserver.openapi.model.catalog.LayerInfo getRootLayer() {
    return rootLayer;
  }


  public void setRootLayer(org.geoserver.openapi.model.catalog.LayerInfo rootLayer) {
    this.rootLayer = rootLayer;
  }


  public LayerGroupInfoAllOf rootLayerStyle(org.geoserver.openapi.model.catalog.StyleInfo rootLayerStyle) {
    
    this.rootLayerStyle = rootLayerStyle;
    return this;
  }

   /**
   * Get rootLayerStyle
   * @return rootLayerStyle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ROOT_LAYER_STYLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public org.geoserver.openapi.model.catalog.StyleInfo getRootLayerStyle() {
    return rootLayerStyle;
  }


  public void setRootLayerStyle(org.geoserver.openapi.model.catalog.StyleInfo rootLayerStyle) {
    this.rootLayerStyle = rootLayerStyle;
  }


  public LayerGroupInfoAllOf layers(List<org.geoserver.openapi.model.catalog.PublishedInfo> layers) {
    
    this.layers = layers;
    return this;
  }

  public LayerGroupInfoAllOf addLayersItem(org.geoserver.openapi.model.catalog.PublishedInfo layersItem) {
    if (this.layers == null) {
      this.layers = new ArrayList<>();
    }
    this.layers.add(layersItem);
    return this;
  }

   /**
   * Get layers
   * @return layers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LAYERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<org.geoserver.openapi.model.catalog.PublishedInfo> getLayers() {
    return layers;
  }


  public void setLayers(List<org.geoserver.openapi.model.catalog.PublishedInfo> layers) {
    this.layers = layers;
  }


  public LayerGroupInfoAllOf styles(List<org.geoserver.openapi.model.catalog.StyleInfo> styles) {
    
    this.styles = styles;
    return this;
  }

  public LayerGroupInfoAllOf addStylesItem(org.geoserver.openapi.model.catalog.StyleInfo stylesItem) {
    if (this.styles == null) {
      this.styles = new ArrayList<>();
    }
    this.styles.add(stylesItem);
    return this;
  }

   /**
   * Get styles
   * @return styles
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STYLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<org.geoserver.openapi.model.catalog.StyleInfo> getStyles() {
    return styles;
  }


  public void setStyles(List<org.geoserver.openapi.model.catalog.StyleInfo> styles) {
    this.styles = styles;
  }


  public LayerGroupInfoAllOf bounds(org.geoserver.openapi.model.catalog.EnvelopeInfo bounds) {
    
    this.bounds = bounds;
    return this;
  }

   /**
   * Get bounds
   * @return bounds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BOUNDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public org.geoserver.openapi.model.catalog.EnvelopeInfo getBounds() {
    return bounds;
  }


  public void setBounds(org.geoserver.openapi.model.catalog.EnvelopeInfo bounds) {
    this.bounds = bounds;
  }


  public LayerGroupInfoAllOf metadataLinks(MetadataLinks metadataLinks) {
    
    this.metadataLinks = metadataLinks;
    return this;
  }

   /**
   * Get metadataLinks
   * @return metadataLinks
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_METADATA_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MetadataLinks getMetadataLinks() {
    return metadataLinks;
  }


  public void setMetadataLinks(MetadataLinks metadataLinks) {
    this.metadataLinks = metadataLinks;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LayerGroupInfoAllOf layerGroupInfoAllOf = (LayerGroupInfoAllOf) o;
    return Objects.equals(this.mode, layerGroupInfoAllOf.mode) &&
        Objects.equals(this.gueryDisabled, layerGroupInfoAllOf.gueryDisabled) &&
        Objects.equals(this.keywords, layerGroupInfoAllOf.keywords) &&
        Objects.equals(this.workspace, layerGroupInfoAllOf.workspace) &&
        Objects.equals(this.rootLayer, layerGroupInfoAllOf.rootLayer) &&
        Objects.equals(this.rootLayerStyle, layerGroupInfoAllOf.rootLayerStyle) &&
        Objects.equals(this.layers, layerGroupInfoAllOf.layers) &&
        Objects.equals(this.styles, layerGroupInfoAllOf.styles) &&
        Objects.equals(this.bounds, layerGroupInfoAllOf.bounds) &&
        Objects.equals(this.metadataLinks, layerGroupInfoAllOf.metadataLinks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mode, gueryDisabled, keywords, workspace, rootLayer, rootLayerStyle, layers, styles, bounds, metadataLinks);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LayerGroupInfoAllOf {\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    gueryDisabled: ").append(toIndentedString(gueryDisabled)).append("\n");
    sb.append("    keywords: ").append(toIndentedString(keywords)).append("\n");
    sb.append("    workspace: ").append(toIndentedString(workspace)).append("\n");
    sb.append("    rootLayer: ").append(toIndentedString(rootLayer)).append("\n");
    sb.append("    rootLayerStyle: ").append(toIndentedString(rootLayerStyle)).append("\n");
    sb.append("    layers: ").append(toIndentedString(layers)).append("\n");
    sb.append("    styles: ").append(toIndentedString(styles)).append("\n");
    sb.append("    bounds: ").append(toIndentedString(bounds)).append("\n");
    sb.append("    metadataLinks: ").append(toIndentedString(metadataLinks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

