/*
 * GeoServer Layers
 * A layer is a published resource (feature type or coverage).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.geoserver.openapi.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.geoserver.openapi.v1.model.NamedLink;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * LayerReference
 */
@JsonPropertyOrder({
  LayerReference.JSON_PROPERTY_LAYER
})

public class LayerReference {
  public static final String JSON_PROPERTY_LAYER = "layer";
  private List<NamedLink> layer = null;


  public LayerReference layer(List<NamedLink> layer) {
    
    this.layer = layer;
    return this;
  }

  public LayerReference addLayerItem(NamedLink layerItem) {
    if (this.layer == null) {
      this.layer = new ArrayList<>();
    }
    this.layer.add(layerItem);
    return this;
  }

   /**
   * Get layer
   * @return layer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LAYER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<NamedLink> getLayer() {
    return layer;
  }


  public void setLayer(List<NamedLink> layer) {
    this.layer = layer;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LayerReference layerReference = (LayerReference) o;
    return Objects.equals(this.layer, layerReference.layer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(layer);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LayerReference {\n");
    sb.append("    layer: ").append(toIndentedString(layer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

