/*
 * GeoServer Namespace
 * A namespace is a uniquely identifiable grouping of feature types. It is identified by a prefix and a URI.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.geoserver.openapi.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.geoserver.openapi.v1.model.NamedLink;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * NamespacesResponseWrapper
 */
@JsonPropertyOrder({
  NamespacesResponseWrapper.JSON_PROPERTY_NAMESPACE
})

public class NamespacesResponseWrapper {
  public static final String JSON_PROPERTY_NAMESPACE = "namespace";
  private List<NamedLink> namespace = null;


  public NamespacesResponseWrapper namespace(List<NamedLink> namespace) {
    
    this.namespace = namespace;
    return this;
  }

  public NamespacesResponseWrapper addNamespaceItem(NamedLink namespaceItem) {
    if (this.namespace == null) {
      this.namespace = new ArrayList<>();
    }
    this.namespace.add(namespaceItem);
    return this;
  }

   /**
   * Get namespace
   * @return namespace
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAMESPACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<NamedLink> getNamespace() {
    return namespace;
  }


  public void setNamespace(List<NamedLink> namespace) {
    this.namespace = namespace;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NamespacesResponseWrapper namespacesResponseWrapper = (NamespacesResponseWrapper) o;
    return Objects.equals(this.namespace, namespacesResponseWrapper.namespace);
  }

  @Override
  public int hashCode() {
    return Objects.hash(namespace);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NamespacesResponseWrapper {\n");
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

