/*
 * GeoServer Coverages
 * A coverage is a raster data set which originates from a coverage store.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.geoserver.openapi.v1.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * StringArrayResponse
 */
@JsonPropertyOrder({
  StringArrayResponse.JSON_PROPERTY_VALUE
})
@Data
@NoArgsConstructor
@AllArgsConstructor
public class StringArrayResponse {
  public static final String JSON_PROPERTY_VALUE = "string";

  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private List<String> values = null;

  public StringArrayResponse addItem(String value) {
    if (this.values == null) {
      this.values = new ArrayList<>();
    }
    this.values.add(value);
    return this;
  }

  public void clear() {
    if(this.values != null) {
      this.values.clear();
    }
  }
}

