/*
 * OWS Services
 * An OWS service refers to any of the OGC services that GeoServer supports, such as WFS, WMS, and WCS. These endpoints controls the settings of these services.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.geoserver.openapi.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * WFSInfoWrapper
 */
@JsonPropertyOrder({
  WFSInfoWrapper.JSON_PROPERTY_WFS
})

public class WFSInfoWrapper {
  public static final String JSON_PROPERTY_WFS = "wfs";
  private org.geoserver.openapi.model.config.WFSInfo wfs = null;


  public WFSInfoWrapper wfs(org.geoserver.openapi.model.config.WFSInfo wfs) {
    
    this.wfs = wfs;
    return this;
  }

   /**
   * Get wfs
   * @return wfs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WFS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public org.geoserver.openapi.model.config.WFSInfo getWfs() {
    return wfs;
  }


  public void setWfs(org.geoserver.openapi.model.config.WFSInfo wfs) {
    this.wfs = wfs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WFSInfoWrapper wfSInfoWrapper = (WFSInfoWrapper) o;
    return Objects.equals(this.wfs, wfSInfoWrapper.wfs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(wfs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WFSInfoWrapper {\n");
    sb.append("    wfs: ").append(toIndentedString(wfs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

