/*
 * GeoServer Workspace
 * A workspace is a grouping of data stores. Similar to a namespace, it is used to group data that is related in some way.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.geoserver.openapi.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.geoserver.openapi.v1.model.WorkspaceResponseWrapper;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * WorkspacesResponse
 */
@JsonPropertyOrder({
  WorkspacesResponse.JSON_PROPERTY_WORKSPACES
})

public class WorkspacesResponse {
  public static final String JSON_PROPERTY_WORKSPACES = "workspaces";
  private WorkspaceResponseWrapper workspaces;


  public WorkspacesResponse workspaces(WorkspaceResponseWrapper workspaces) {
    
    this.workspaces = workspaces;
    return this;
  }

   /**
   * Get workspaces
   * @return workspaces
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WORKSPACES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public WorkspaceResponseWrapper getWorkspaces() {
    return workspaces;
  }


  public void setWorkspaces(WorkspaceResponseWrapper workspaces) {
    this.workspaces = workspaces;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkspacesResponse workspacesResponse = (WorkspacesResponse) o;
    return Objects.equals(this.workspaces, workspacesResponse.workspaces);
  }

  @Override
  public int hashCode() {
    return Objects.hash(workspaces);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkspacesResponse {\n");
    sb.append("    workspaces: ").append(toIndentedString(workspaces)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

